[mypy]
python_version = 3.12
strict = True
exclude = migrations/|\.venv/
plugins = pydantic.mypy

[mypy-razorpay.*]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-aiosmtplib.*]
ignore_missing_imports = True
