from enum import StrEnum


class ErrorCode(StrEnum):
    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BAD_REQUEST = "BAD_REQUEST"

    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"

    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED"

    # Book
    BOOK_NOT_FOUND = "BOOK_NOT_FOUND"
    BOOK_ALREADY_EXISTS = "BOOK_ALREADY_EXISTS"
    INVALID_ISBN = "INVALID_ISBN"

    # Order
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_ALREADY_PAID = "ORDER_ALREADY_PAID"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    EMPTY_ORDER = "EMPTY_ORDER"

    # Storage / Payment
    STORAGE_UPLOAD_FAILED = "STORAGE_UPLOAD_FAILED"
    PAYMENT_CREATION_FAILED = "PAYMENT_CREATION_FAILED"
    PAYMENT_VERIFICATION_FAILED = "PAYMENT_VERIFICATION_FAILED"

    # HTTP
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"
