from enum import StrEnum


class ErrorCode(StrEnum):
    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BAD_REQUEST = "BAD_REQUEST"

    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    NOT_AUTH_HEADER = "NO_AUTH_HEADER"
    CURRENT_PASSWORD_INCORRECT = "CURRENT_PASSWORD_INCORRECT"
    PASSWORD_NOT_SET = "PASSWORD_NOT_SET"
    NEW_PASSWORD_SAME_AS_CURRENT = "NEW_PASSWORD_SAME_AS_CURRENT"

    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED"
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"
    USER_SUSPENDED = "USER_SUSPENDED"
    USER_ALREADY_SUSPENDED = "USER_ALREADY_SUSPENDED"
    CANNOT_SUSPEND_ADMIN = "CANNOT_SUSPEND_ADMIN"
    USER_ALREADY_ACTIVE = "USER_ALREADY_ACTIVE"
    CANNOT_ACTIVATE_PENDING_USER = "CANNOT_ACTIVATE_PENDING_USER"

    # Book
    BOOK_NOT_FOUND = "BOOK_NOT_FOUND"
    BOOK_ALREADY_EXISTS = "BOOK_ALREADY_EXISTS"
    INVALID_ISBN = "INVALID_ISBN"
    BOOK_ALREADY_DEACTIVATED = "BOOK_ALREADY_DEACTIVATED"
    BOOK_ALREADY_ACTIVATED = "BOOK_ALREADY_ACTIVATED"

    # Order
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_ALREADY_PAID = "ORDER_ALREADY_PAID"
    ORDER_NOT_PAYABLE = "ORDER_NOT_PAYABLE"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    EMPTY_ORDER = "EMPTY_ORDER"
    ORDER_ACCESS_DENIED = "ORDER_ACCESS_DENIED"
    ORDER_NOT_CANCELLABLE = "ORDER_NOT_CANCELLABLE"
    ORDER_STATUS_TRANSITION_INVALID = "ORDER_STATUS_TRANSITION_INVALID"

    # Payment
    PAYMENT_CREATION_FAILED = "PAYMENT_CREATION_FAILED"
    PAYMENT_VERIFICATION_FAILED = "PAYMENT_VERIFICATION_FAILED"

    # HTTP
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"

    # Admin
    ADMIN_ACCESS_REQUIRED = "ADMIN_ACCESS_REQUIRED"

    # OAuth
    OAUTH_STATE_INVALID = "OAUTH_STATE_INVALID"
    OAUTH_PROVIDER_NOT_FOUND = "OAUTH_PROVIDER_NOT_FOUND"
    GOOGLE_OAUTH_ERROR = "GOOGLE_OAUTH_ERROR"
    FACEBOOK_OAUTH_ERROR = "FACEBOOK_OAUTH_ERROR"

    # Storage
    STORAGE_UPLOAD_FAILED = "STORAGE_UPLOAD_FAILED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"

    # Address
    ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND"

    # Collection
    COLLECTION_ALREADY_EXISTS = "COLLECTION_ALREADY_EXISTS"
    COLLECTION_NOT_FOUND = "COLLECTION_NOT_FOUND"

    # Category
    CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS"
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"

    # Author
    AUTHOR_NOT_FOUND = "AUTHOR_NOT_FOUND"

    # Publisher
    PUBLISHER_NOT_FOUND = "PUBLISHER_NOT_FOUND"

    # Cart
    CART_NOT_FOUND = "CART_NOT_FOUND"
    CART_ITEM_NOT_FOUND = "CART_ITEM_NOT_FOUND"

    # Review
    REVIEW_NOT_ELIGIBLE = "REVIEW_NOT_ELIGIBLE"
    REVIEW_ALREADY_EXISTS = "REVIEW_ALREADY_EXISTS"
    REVIEW_NOT_FOUND = "REVIEW_NOT_FOUND"
    REVIEW_NOT_OWNED = "REVIEW_NOT_OWNED"

    # Wishlist
    WISHLIST_ITEM_ALREADY_EXISTS_FOUND = "WISHLIST_ITEM_ALREADY_EXISTS"
    WISHLIST_NOT_FOUND = "WISHLIST_NOT_FOUND"
    WISHLIST_ITEM_NOT_FOUND = "WISHLIST_ITEM_NOT_FOUND"
