from enum import StrEnum


class ErrorCode(StrEnum):
    # Generic
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    BAD_REQUEST = "BAD_REQUEST"

    # Auth
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    TOKEN_REVOKED = "TOKEN_REVOKED"
    NOT_AUTH_HEADER = "NO_AUTH_HEADER"
    CURRENT_PASSWORD_INCORRECT = "CURRENT_PASSWORD_INCORRECT"
    PASSWORD_NOT_SET = "PASSWORD_NOT_SET"
    NEW_PASSWORD_SAME_AS_CURRENT = "NEW_PASSWORD_SAME_AS_CURRENT"

    # User
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED"
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"
    USER_SUSPENDED = "USER_SUSPENDED"

    # Book
    BOOK_NOT_FOUND = "BOOK_NOT_FOUND"
    BOOK_ALREADY_EXISTS = "BOOK_ALREADY_EXISTS"
    INVALID_ISBN = "INVALID_ISBN"

    # Order
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_ALREADY_PAID = "ORDER_ALREADY_PAID"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    EMPTY_ORDER = "EMPTY_ORDER"

    # Payment
    PAYMENT_CREATION_FAILED = "PAYMENT_CREATION_FAILED"
    PAYMENT_VERIFICATION_FAILED = "PAYMENT_VERIFICATION_FAILED"

    # HTTP
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    CONFLICT = "CONFLICT"
    RATE_LIMITED = "RATE_LIMITED"

    # Admin
    ADMIN_ACCESS_REQUIRED = "ADMIN_ACCESS_REQUIRED"

    # OAuth
    OAUTH_STATE_INVALID = "OAUTH_STATE_INVALID"
    OAUTH_PROVIDER_NOT_FOUND = "OAUTH_PROVIDER_NOT_FOUND"
    GOOGLE_OAUTH_ERROR = "GOOGLE_OAUTH_ERROR"
    FACEBOOK_OAUTH_ERROR = "FACEBOOK_OAUTH_ERROR"

    # Storage
    STORAGE_UPLOAD_FAILED = "STORAGE_UPLOAD_FAILED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"

    # Address
    ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND"

    # Collection
    COLLECTION_ALREADY_EXISTS = "COLLECTION_ALREADY_EXISTS"
    COLLECTION_NOT_FOUND = "COLLECTION_NOT_FOUND"

    # Category
    CATEGORY_ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS"
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"

    # Author
    AUTHOR_NOT_FOUND = "AUTHOR_NOT_FOUND"
