"""add report job table

Revision ID: d99fb43f33ac
Revises: 6cba05eb288f
Create Date: 2026-05-20 19:42:33.260872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.infrastructure.db.models import types
from app.core.constants import ReportType, ReportJobStatus, ReportFormat

# revision identifiers, used by Alembic.
revision: str = 'd99fb43f33ac'
down_revision: Union[str, Sequence[str], None] = '6cba05eb288f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_jobs',
    sa.Column('admin_id', sa.String(length=255), nullable=False),
    sa.Column('report_type', types.EnumText(ReportType, length=50), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('report_format', types.EnumText(ReportFormat, length=10), nullable=False),
    sa.Column('status', types.EnumText(ReportJobStatus, length=10), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_report_jobs_admin_id', 'report_jobs', ['admin_id'], unique=False)
    op.create_index('idx_report_jobs_status', 'report_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_report_jobs_status', table_name='report_jobs')
    op.drop_index('idx_report_jobs_admin_id', table_name='report_jobs')
    op.drop_table('report_jobs')
    # ### end Alembic commands ###
