"""alter review add hidden at column

Revision ID: 65b0d23dc68e
Revises: e6aa3b906470
Create Date: 2026-05-17 10:49:55.134453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b0d23dc68e'
down_revision: Union[str, Sequence[str], None] = 'e6aa3b906470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'hidden_at')
    # ### end Alembic commands ###
