"""alter publisher add deleted_at column

Revision ID: e6aa3b906470
Revises: 411cc493b898
Create Date: 2026-05-15 09:44:47.209609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6aa3b906470'
down_revision: Union[str, Sequence[str], None] = '411cc493b898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publishers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publishers', 'deleted_at')
    # ### end Alembic commands ###
