"""create_verification_tokens_table

Revision ID: 48481663a72f
Revises: 6db49f674c10
Create Date: 2026-05-03 20:25:16.718993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.infrastructure.db.models import types
from app.core.constants import VerificationTokenType
# revision identifiers, used by Alembic.
revision: str = '48481663a72f'
down_revision: Union[str, Sequence[str], None] = '6db49f674c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('type', types.EnumText(VerificationTokenType, length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_verification_tokens_expires_at', 'verification_tokens', ['expires_at'], unique=False)
    op.create_index('idx_verification_tokens_user_id_type', 'verification_tokens', ['user_id', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_verification_tokens_user_id_type', table_name='verification_tokens')
    op.drop_index('idx_verification_tokens_expires_at', table_name='verification_tokens')
    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
