/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddCartItemRequest
 */
export interface AddCartItemRequest {
    /**
     * 
     * @type {number}
     * @memberof AddCartItemRequest
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof AddCartItemRequest
     */
    bookId: string;
}

/**
 * Check if a given object implements the AddCartItemRequest interface.
 */
export function instanceOfAddCartItemRequest(value: object): value is AddCartItemRequest {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    return true;
}

export function AddCartItemRequestFromJSON(json: any): AddCartItemRequest {
    return AddCartItemRequestFromJSONTyped(json, false);
}

export function AddCartItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCartItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'bookId': json['book_id'],
    };
}

export function AddCartItemRequestToJSON(json: any): AddCartItemRequest {
    return AddCartItemRequestToJSONTyped(json, false);
}

export function AddCartItemRequestToJSONTyped(value?: AddCartItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'book_id': value['bookId'],
    };
}

