/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CartItemBookResponse } from './CartItemBookResponse';
import {
    CartItemBookResponseFromJSON,
    CartItemBookResponseFromJSONTyped,
    CartItemBookResponseToJSON,
    CartItemBookResponseToJSONTyped,
} from './CartItemBookResponse';

/**
 * 
 * @export
 * @interface AddCartItemResponse
 */
export interface AddCartItemResponse {
    /**
     * 
     * @type {string}
     * @memberof AddCartItemResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AddCartItemResponse
     */
    cartId: string;
    /**
     * 
     * @type {string}
     * @memberof AddCartItemResponse
     */
    bookId: string;
    /**
     * 
     * @type {number}
     * @memberof AddCartItemResponse
     */
    quantity: number;
    /**
     * 
     * @type {CartItemBookResponse}
     * @memberof AddCartItemResponse
     */
    book: CartItemBookResponse;
}

/**
 * Check if a given object implements the AddCartItemResponse interface.
 */
export function instanceOfAddCartItemResponse(value: object): value is AddCartItemResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('cartId' in value) || value['cartId'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    return true;
}

export function AddCartItemResponseFromJSON(json: any): AddCartItemResponse {
    return AddCartItemResponseFromJSONTyped(json, false);
}

export function AddCartItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCartItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'cartId': json['cart_id'],
        'bookId': json['book_id'],
        'quantity': json['quantity'],
        'book': CartItemBookResponseFromJSON(json['book']),
    };
}

export function AddCartItemResponseToJSON(json: any): AddCartItemResponse {
    return AddCartItemResponseToJSONTyped(json, false);
}

export function AddCartItemResponseToJSONTyped(value?: AddCartItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'cart_id': value['cartId'],
        'book_id': value['bookId'],
        'quantity': value['quantity'],
        'book': CartItemBookResponseToJSON(value['book']),
    };
}

