/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddWishlistItemRequest
 */
export interface AddWishlistItemRequest {
    /**
     * 
     * @type {string}
     * @memberof AddWishlistItemRequest
     */
    bookId: string;
}

/**
 * Check if a given object implements the AddWishlistItemRequest interface.
 */
export function instanceOfAddWishlistItemRequest(value: object): value is AddWishlistItemRequest {
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    return true;
}

export function AddWishlistItemRequestFromJSON(json: any): AddWishlistItemRequest {
    return AddWishlistItemRequestFromJSONTyped(json, false);
}

export function AddWishlistItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddWishlistItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bookId': json['book_id'],
    };
}

export function AddWishlistItemRequestToJSON(json: any): AddWishlistItemRequest {
    return AddWishlistItemRequestToJSONTyped(json, false);
}

export function AddWishlistItemRequestToJSONTyped(value?: AddWishlistItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'book_id': value['bookId'],
    };
}

