/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WishlistItemBookResponse } from './WishlistItemBookResponse';
import {
    WishlistItemBookResponseFromJSON,
    WishlistItemBookResponseFromJSONTyped,
    WishlistItemBookResponseToJSON,
    WishlistItemBookResponseToJSONTyped,
} from './WishlistItemBookResponse';

/**
 * 
 * @export
 * @interface AddWishlistItemResponse
 */
export interface AddWishlistItemResponse {
    /**
     * 
     * @type {string}
     * @memberof AddWishlistItemResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AddWishlistItemResponse
     */
    wishlistId: string;
    /**
     * 
     * @type {string}
     * @memberof AddWishlistItemResponse
     */
    bookId: string;
    /**
     * 
     * @type {Date}
     * @memberof AddWishlistItemResponse
     */
    addedAt: Date;
    /**
     * 
     * @type {WishlistItemBookResponse}
     * @memberof AddWishlistItemResponse
     */
    book: WishlistItemBookResponse;
}

/**
 * Check if a given object implements the AddWishlistItemResponse interface.
 */
export function instanceOfAddWishlistItemResponse(value: object): value is AddWishlistItemResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('wishlistId' in value) || value['wishlistId'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('addedAt' in value) || value['addedAt'] === undefined) return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    return true;
}

export function AddWishlistItemResponseFromJSON(json: any): AddWishlistItemResponse {
    return AddWishlistItemResponseFromJSONTyped(json, false);
}

export function AddWishlistItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddWishlistItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'wishlistId': json['wishlist_id'],
        'bookId': json['book_id'],
        'addedAt': (new Date(json['added_at'])),
        'book': WishlistItemBookResponseFromJSON(json['book']),
    };
}

export function AddWishlistItemResponseToJSON(json: any): AddWishlistItemResponse {
    return AddWishlistItemResponseToJSONTyped(json, false);
}

export function AddWishlistItemResponseToJSONTyped(value?: AddWishlistItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'wishlist_id': value['wishlistId'],
        'book_id': value['bookId'],
        'added_at': ((value['addedAt']).toISOString()),
        'book': WishlistItemBookResponseToJSON(value['book']),
    };
}

