/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BaseCategoryResponse
 */
export interface BaseCategoryResponse {
    /**
     * 
     * @type {string}
     * @memberof BaseCategoryResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BaseCategoryResponse
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof BaseCategoryResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BaseCategoryResponse
     */
    urlSlug: string;
    /**
     * 
     * @type {Date}
     * @memberof BaseCategoryResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the BaseCategoryResponse interface.
 */
export function instanceOfBaseCategoryResponse(value: object): value is BaseCategoryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('urlSlug' in value) || value['urlSlug'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function BaseCategoryResponseFromJSON(json: any): BaseCategoryResponse {
    return BaseCategoryResponseFromJSONTyped(json, false);
}

export function BaseCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BaseCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'collectionId': json['collection_id'],
        'name': json['name'],
        'urlSlug': json['url_slug'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function BaseCategoryResponseToJSON(json: any): BaseCategoryResponse {
    return BaseCategoryResponseToJSONTyped(json, false);
}

export function BaseCategoryResponseToJSONTyped(value?: BaseCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'collection_id': value['collectionId'],
        'name': value['name'],
        'url_slug': value['urlSlug'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

