/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CardPaymentRequest } from './CardPaymentRequest';
import {
    instanceOfCardPaymentRequest,
    CardPaymentRequestFromJSON,
    CardPaymentRequestFromJSONTyped,
    CardPaymentRequestToJSON,
} from './CardPaymentRequest';
import type { OnlineBankingPaymentRequest } from './OnlineBankingPaymentRequest';
import {
    instanceOfOnlineBankingPaymentRequest,
    OnlineBankingPaymentRequestFromJSON,
    OnlineBankingPaymentRequestFromJSONTyped,
    OnlineBankingPaymentRequestToJSON,
} from './OnlineBankingPaymentRequest';

/**
 * @type Body
 * 
 * @export
 */
export type Body = { paymentMethod: 'card' } & CardPaymentRequest | { paymentMethod: 'online_banking' } & OnlineBankingPaymentRequest;

export function BodyFromJSON(json: any): Body {
    return BodyFromJSONTyped(json, false);
}

export function BodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Body {
    if (json == null) {
        return json;
    }
    switch (json['payment_method']) {
        case 'card':
            return Object.assign({}, CardPaymentRequestFromJSONTyped(json, true), { paymentMethod: 'card' } as const);
        case 'online_banking':
            return Object.assign({}, OnlineBankingPaymentRequestFromJSONTyped(json, true), { paymentMethod: 'online_banking' } as const);
        default:
            throw new Error(`No variant of Body exists with 'paymentMethod=${json['paymentMethod']}'`);
    }
}

export function BodyToJSON(json: any): any {
    return BodyToJSONTyped(json, false);
}

export function BodyToJSONTyped(value?: Body | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['paymentMethod']) {
        case 'card':
            return Object.assign({}, CardPaymentRequestToJSON(value), { paymentMethod: 'card' } as const);
        case 'online_banking':
            return Object.assign({}, OnlineBankingPaymentRequestToJSON(value), { paymentMethod: 'online_banking' } as const);
        default:
            throw new Error(`No variant of Body exists with 'paymentMethod=${value['paymentMethod']}'`);
    }

}

