/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookAuthorItemRequest
 */
export interface BookAuthorItemRequest {
    /**
     * 
     * @type {string}
     * @memberof BookAuthorItemRequest
     */
    authorId: string;
    /**
     * 
     * @type {number}
     * @memberof BookAuthorItemRequest
     */
    displayOrder: number;
}

/**
 * Check if a given object implements the BookAuthorItemRequest interface.
 */
export function instanceOfBookAuthorItemRequest(value: object): value is BookAuthorItemRequest {
    if (!('authorId' in value) || value['authorId'] === undefined) return false;
    if (!('displayOrder' in value) || value['displayOrder'] === undefined) return false;
    return true;
}

export function BookAuthorItemRequestFromJSON(json: any): BookAuthorItemRequest {
    return BookAuthorItemRequestFromJSONTyped(json, false);
}

export function BookAuthorItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookAuthorItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'authorId': json['author_id'],
        'displayOrder': json['display_order'],
    };
}

export function BookAuthorItemRequestToJSON(json: any): BookAuthorItemRequest {
    return BookAuthorItemRequestToJSONTyped(json, false);
}

export function BookAuthorItemRequestToJSONTyped(value?: BookAuthorItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author_id': value['authorId'],
        'display_order': value['displayOrder'],
    };
}

