/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
    OrderStatusToJSONTyped,
} from './OrderStatus';

/**
 * 
 * @export
 * @interface CancelOrderResponse
 */
export interface CancelOrderResponse {
    /**
     * 
     * @type {string}
     * @memberof CancelOrderResponse
     */
    id: string;
    /**
     * 
     * @type {OrderStatus}
     * @memberof CancelOrderResponse
     */
    status: OrderStatus;
    /**
     * 
     * @type {Date}
     * @memberof CancelOrderResponse
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the CancelOrderResponse interface.
 */
export function instanceOfCancelOrderResponse(value: object): value is CancelOrderResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CancelOrderResponseFromJSON(json: any): CancelOrderResponse {
    return CancelOrderResponseFromJSONTyped(json, false);
}

export function CancelOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': OrderStatusFromJSON(json['status']),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function CancelOrderResponseToJSON(json: any): CancelOrderResponse {
    return CancelOrderResponseToJSONTyped(json, false);
}

export function CancelOrderResponseToJSONTyped(value?: CancelOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': OrderStatusToJSON(value['status']),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

