/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordResponse
 */
export interface ChangePasswordResponse {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ChangePasswordResponse interface.
 */
export function instanceOfChangePasswordResponse(value: object): value is ChangePasswordResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ChangePasswordResponseFromJSON(json: any): ChangePasswordResponse {
    return ChangePasswordResponseFromJSONTyped(json, false);
}

export function ChangePasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ChangePasswordResponseToJSON(json: any): ChangePasswordResponse {
    return ChangePasswordResponseToJSONTyped(json, false);
}

export function ChangePasswordResponseToJSONTyped(value?: ChangePasswordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

