/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseCartItemResponse } from './BaseCartItemResponse';
import {
    BaseCartItemResponseFromJSON,
    BaseCartItemResponseFromJSONTyped,
    BaseCartItemResponseToJSON,
    BaseCartItemResponseToJSONTyped,
} from './BaseCartItemResponse';

/**
 * 
 * @export
 * @interface ClearAllCartItemsResponse
 */
export interface ClearAllCartItemsResponse {
    /**
     * 
     * @type {string}
     * @memberof ClearAllCartItemsResponse
     */
    id: string;
    /**
     * 
     * @type {Array<BaseCartItemResponse>}
     * @memberof ClearAllCartItemsResponse
     */
    items: Array<BaseCartItemResponse>;
}

/**
 * Check if a given object implements the ClearAllCartItemsResponse interface.
 */
export function instanceOfClearAllCartItemsResponse(value: object): value is ClearAllCartItemsResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ClearAllCartItemsResponseFromJSON(json: any): ClearAllCartItemsResponse {
    return ClearAllCartItemsResponseFromJSONTyped(json, false);
}

export function ClearAllCartItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClearAllCartItemsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'items': ((json['items'] as Array<any>).map(BaseCartItemResponseFromJSON)),
    };
}

export function ClearAllCartItemsResponseToJSON(json: any): ClearAllCartItemsResponse {
    return ClearAllCartItemsResponseToJSONTyped(json, false);
}

export function ClearAllCartItemsResponseToJSONTyped(value?: ClearAllCartItemsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'items': ((value['items'] as Array<any>).map(BaseCartItemResponseToJSON)),
    };
}

