/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseCategoryResponse } from './BaseCategoryResponse';
import {
    BaseCategoryResponseFromJSON,
    BaseCategoryResponseFromJSONTyped,
    BaseCategoryResponseToJSON,
    BaseCategoryResponseToJSONTyped,
} from './BaseCategoryResponse';

/**
 * 
 * @export
 * @interface CollectionListItemResponse
 */
export interface CollectionListItemResponse {
    /**
     * 
     * @type {string}
     * @memberof CollectionListItemResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionListItemResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CollectionListItemResponse
     */
    urlSlug: string;
    /**
     * 
     * @type {Array<BaseCategoryResponse>}
     * @memberof CollectionListItemResponse
     */
    categories: Array<BaseCategoryResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CollectionListItemResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CollectionListItemResponse interface.
 */
export function instanceOfCollectionListItemResponse(value: object): value is CollectionListItemResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('urlSlug' in value) || value['urlSlug'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CollectionListItemResponseFromJSON(json: any): CollectionListItemResponse {
    return CollectionListItemResponseFromJSONTyped(json, false);
}

export function CollectionListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'urlSlug': json['url_slug'],
        'categories': ((json['categories'] as Array<any>).map(BaseCategoryResponseFromJSON)),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function CollectionListItemResponseToJSON(json: any): CollectionListItemResponse {
    return CollectionListItemResponseToJSONTyped(json, false);
}

export function CollectionListItemResponseToJSONTyped(value?: CollectionListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url_slug': value['urlSlug'],
        'categories': ((value['categories'] as Array<any>).map(BaseCategoryResponseToJSON)),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

