/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryResponse } from './CategoryResponse';
import {
    CategoryResponseFromJSON,
    CategoryResponseFromJSONTyped,
    CategoryResponseToJSON,
    CategoryResponseToJSONTyped,
} from './CategoryResponse';

/**
 * 
 * @export
 * @interface CreateCollectionResponse
 */
export interface CreateCollectionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCollectionResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCollectionResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCollectionResponse
     */
    urlSlug: string;
    /**
     * 
     * @type {Array<CategoryResponse>}
     * @memberof CreateCollectionResponse
     */
    categories: Array<CategoryResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CreateCollectionResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CreateCollectionResponse interface.
 */
export function instanceOfCreateCollectionResponse(value: object): value is CreateCollectionResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('urlSlug' in value) || value['urlSlug'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreateCollectionResponseFromJSON(json: any): CreateCollectionResponse {
    return CreateCollectionResponseFromJSONTyped(json, false);
}

export function CreateCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'urlSlug': json['url_slug'],
        'categories': ((json['categories'] as Array<any>).map(CategoryResponseFromJSON)),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function CreateCollectionResponseToJSON(json: any): CreateCollectionResponse {
    return CreateCollectionResponseToJSONTyped(json, false);
}

export function CreateCollectionResponseToJSONTyped(value?: CreateCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url_slug': value['urlSlug'],
        'categories': ((value['categories'] as Array<any>).map(CategoryResponseToJSON)),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

