/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuthorRequest
 */
export interface CreateAuthorRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorRequest
     */
    name: string;
}

/**
 * Check if a given object implements the CreateAuthorRequest interface.
 */
export function instanceOfCreateAuthorRequest(value: object): value is CreateAuthorRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateAuthorRequestFromJSON(json: any): CreateAuthorRequest {
    return CreateAuthorRequestFromJSONTyped(json, false);
}

export function CreateAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuthorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CreateAuthorRequestToJSON(json: any): CreateAuthorRequest {
    return CreateAuthorRequestToJSONTyped(json, false);
}

export function CreateAuthorRequestToJSONTyped(value?: CreateAuthorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

