/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePublisherResponse
 */
export interface CreatePublisherResponse {
    /**
     * 
     * @type {string}
     * @memberof CreatePublisherResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublisherResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublisherResponse
     */
    website: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreatePublisherResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CreatePublisherResponse interface.
 */
export function instanceOfCreatePublisherResponse(value: object): value is CreatePublisherResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreatePublisherResponseFromJSON(json: any): CreatePublisherResponse {
    return CreatePublisherResponseFromJSONTyped(json, false);
}

export function CreatePublisherResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePublisherResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'website': json['website'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function CreatePublisherResponseToJSON(json: any): CreatePublisherResponse {
    return CreatePublisherResponseToJSONTyped(json, false);
}

export function CreatePublisherResponseToJSONTyped(value?: CreatePublisherResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'website': value['website'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

