/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportFormat } from './ReportFormat';
import {
    ReportFormatFromJSON,
    ReportFormatFromJSONTyped,
    ReportFormatToJSON,
    ReportFormatToJSONTyped,
} from './ReportFormat';
import type { ReportType } from './ReportType';
import {
    ReportTypeFromJSON,
    ReportTypeFromJSONTyped,
    ReportTypeToJSON,
    ReportTypeToJSONTyped,
} from './ReportType';

/**
 * 
 * @export
 * @interface CreateReportJobRequest
 */
export interface CreateReportJobRequest {
    /**
     * 
     * @type {ReportType}
     * @memberof CreateReportJobRequest
     */
    type: ReportType;
    /**
     * 
     * @type {Date}
     * @memberof CreateReportJobRequest
     */
    dateFrom: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateReportJobRequest
     */
    dateTo: Date;
    /**
     * 
     * @type {ReportFormat}
     * @memberof CreateReportJobRequest
     */
    format: ReportFormat;
    /**
     * 
     * @type {number}
     * @memberof CreateReportJobRequest
     */
    limit?: number | null;
}



/**
 * Check if a given object implements the CreateReportJobRequest interface.
 */
export function instanceOfCreateReportJobRequest(value: object): value is CreateReportJobRequest {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('dateFrom' in value) || value['dateFrom'] === undefined) return false;
    if (!('dateTo' in value) || value['dateTo'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    return true;
}

export function CreateReportJobRequestFromJSON(json: any): CreateReportJobRequest {
    return CreateReportJobRequestFromJSONTyped(json, false);
}

export function CreateReportJobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReportJobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': ReportTypeFromJSON(json['type']),
        'dateFrom': (new Date(json['date_from'])),
        'dateTo': (new Date(json['date_to'])),
        'format': ReportFormatFromJSON(json['format']),
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function CreateReportJobRequestToJSON(json: any): CreateReportJobRequest {
    return CreateReportJobRequestToJSONTyped(json, false);
}

export function CreateReportJobRequestToJSONTyped(value?: CreateReportJobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': ReportTypeToJSON(value['type']),
        'date_from': ((value['dateFrom']).toISOString().substring(0,10)),
        'date_to': ((value['dateTo']).toISOString().substring(0,10)),
        'format': ReportFormatToJSON(value['format']),
        'limit': value['limit'],
    };
}

