/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAuthorResponse
 */
export interface CreateAuthorResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAuthorResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateAuthorResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the CreateAuthorResponse interface.
 */
export function instanceOfCreateAuthorResponse(value: object): value is CreateAuthorResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreateAuthorResponseFromJSON(json: any): CreateAuthorResponse {
    return CreateAuthorResponseFromJSONTyped(json, false);
}

export function CreateAuthorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAuthorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function CreateAuthorResponseToJSON(json: any): CreateAuthorResponse {
    return CreateAuthorResponseToJSONTyped(json, false);
}

export function CreateAuthorResponseToJSONTyped(value?: CreateAuthorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

