/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCategoryRequest
 */
export interface CreateCategoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    collectionId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCategoryRequest
     */
    urlSlug: string;
}

/**
 * Check if a given object implements the CreateCategoryRequest interface.
 */
export function instanceOfCreateCategoryRequest(value: object): value is CreateCategoryRequest {
    if (!('collectionId' in value) || value['collectionId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('urlSlug' in value) || value['urlSlug'] === undefined) return false;
    return true;
}

export function CreateCategoryRequestFromJSON(json: any): CreateCategoryRequest {
    return CreateCategoryRequestFromJSONTyped(json, false);
}

export function CreateCategoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCategoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'collectionId': json['collection_id'],
        'name': json['name'],
        'urlSlug': json['url_slug'],
    };
}

export function CreateCategoryRequestToJSON(json: any): CreateCategoryRequest {
    return CreateCategoryRequestToJSONTyped(json, false);
}

export function CreateCategoryRequestToJSONTyped(value?: CreateCategoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection_id': value['collectionId'],
        'name': value['name'],
        'url_slug': value['urlSlug'],
    };
}

