/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePublisherRequest
 */
export interface CreatePublisherRequest {
    /**
     * 
     * @type {string}
     * @memberof CreatePublisherRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublisherRequest
     */
    website?: string | null;
}

/**
 * Check if a given object implements the CreatePublisherRequest interface.
 */
export function instanceOfCreatePublisherRequest(value: object): value is CreatePublisherRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreatePublisherRequestFromJSON(json: any): CreatePublisherRequest {
    return CreatePublisherRequestFromJSONTyped(json, false);
}

export function CreatePublisherRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePublisherRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'website': json['website'] == null ? undefined : json['website'],
    };
}

export function CreatePublisherRequestToJSON(json: any): CreatePublisherRequest {
    return CreatePublisherRequestToJSONTyped(json, false);
}

export function CreatePublisherRequestToJSONTyped(value?: CreatePublisherRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'website': value['website'],
    };
}

