/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForceSetUserPasswordResponse
 */
export interface ForceSetUserPasswordResponse {
    /**
     * 
     * @type {string}
     * @memberof ForceSetUserPasswordResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ForceSetUserPasswordResponse interface.
 */
export function instanceOfForceSetUserPasswordResponse(value: object): value is ForceSetUserPasswordResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ForceSetUserPasswordResponseFromJSON(json: any): ForceSetUserPasswordResponse {
    return ForceSetUserPasswordResponseFromJSONTyped(json, false);
}

export function ForceSetUserPasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForceSetUserPasswordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ForceSetUserPasswordResponseToJSON(json: any): ForceSetUserPasswordResponse {
    return ForceSetUserPasswordResponseToJSONTyped(json, false);
}

export function ForceSetUserPasswordResponseToJSONTyped(value?: ForceSetUserPasswordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

