/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordResponse
 */
export interface ForgotPasswordResponse {
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ForgotPasswordResponse interface.
 */
export function instanceOfForgotPasswordResponse(value: object): value is ForgotPasswordResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ForgotPasswordResponseFromJSON(json: any): ForgotPasswordResponse {
    return ForgotPasswordResponseFromJSONTyped(json, false);
}

export function ForgotPasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ForgotPasswordResponseToJSON(json: any): ForgotPasswordResponse {
    return ForgotPasswordResponseToJSONTyped(json, false);
}

export function ForgotPasswordResponseToJSONTyped(value?: ForgotPasswordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

