/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseWishlistItemResponse } from './BaseWishlistItemResponse';
import {
    BaseWishlistItemResponseFromJSON,
    BaseWishlistItemResponseFromJSONTyped,
    BaseWishlistItemResponseToJSON,
    BaseWishlistItemResponseToJSONTyped,
} from './BaseWishlistItemResponse';

/**
 * 
 * @export
 * @interface GetMyWishlistResponse
 */
export interface GetMyWishlistResponse {
    /**
     * 
     * @type {string}
     * @memberof GetMyWishlistResponse
     */
    id: string;
    /**
     * 
     * @type {Array<BaseWishlistItemResponse>}
     * @memberof GetMyWishlistResponse
     */
    items: Array<BaseWishlistItemResponse>;
}

/**
 * Check if a given object implements the GetMyWishlistResponse interface.
 */
export function instanceOfGetMyWishlistResponse(value: object): value is GetMyWishlistResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GetMyWishlistResponseFromJSON(json: any): GetMyWishlistResponse {
    return GetMyWishlistResponseFromJSONTyped(json, false);
}

export function GetMyWishlistResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyWishlistResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'items': ((json['items'] as Array<any>).map(BaseWishlistItemResponseFromJSON)),
    };
}

export function GetMyWishlistResponseToJSON(json: any): GetMyWishlistResponse {
    return GetMyWishlistResponseToJSONTyped(json, false);
}

export function GetMyWishlistResponseToJSONTyped(value?: GetMyWishlistResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'items': ((value['items'] as Array<any>).map(BaseWishlistItemResponseToJSON)),
    };
}

