/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseCartItemResponse } from './BaseCartItemResponse';
import {
    BaseCartItemResponseFromJSON,
    BaseCartItemResponseFromJSONTyped,
    BaseCartItemResponseToJSON,
    BaseCartItemResponseToJSONTyped,
} from './BaseCartItemResponse';

/**
 * 
 * @export
 * @interface GetMyCartResponse
 */
export interface GetMyCartResponse {
    /**
     * 
     * @type {string}
     * @memberof GetMyCartResponse
     */
    id: string;
    /**
     * 
     * @type {Array<BaseCartItemResponse>}
     * @memberof GetMyCartResponse
     */
    items: Array<BaseCartItemResponse>;
}

/**
 * Check if a given object implements the GetMyCartResponse interface.
 */
export function instanceOfGetMyCartResponse(value: object): value is GetMyCartResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function GetMyCartResponseFromJSON(json: any): GetMyCartResponse {
    return GetMyCartResponseFromJSONTyped(json, false);
}

export function GetMyCartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMyCartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'items': ((json['items'] as Array<any>).map(BaseCartItemResponseFromJSON)),
    };
}

export function GetMyCartResponseToJSON(json: any): GetMyCartResponse {
    return GetMyCartResponseToJSONTyped(json, false);
}

export function GetMyCartResponseToJSONTyped(value?: GetMyCartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'items': ((value['items'] as Array<any>).map(BaseCartItemResponseToJSON)),
    };
}

