/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HideOrRestoreReviewRequest
 */
export interface HideOrRestoreReviewRequest {
    /**
     * 
     * @type {boolean}
     * @memberof HideOrRestoreReviewRequest
     */
    isHidden: boolean;
}

/**
 * Check if a given object implements the HideOrRestoreReviewRequest interface.
 */
export function instanceOfHideOrRestoreReviewRequest(value: object): value is HideOrRestoreReviewRequest {
    if (!('isHidden' in value) || value['isHidden'] === undefined) return false;
    return true;
}

export function HideOrRestoreReviewRequestFromJSON(json: any): HideOrRestoreReviewRequest {
    return HideOrRestoreReviewRequestFromJSONTyped(json, false);
}

export function HideOrRestoreReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HideOrRestoreReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isHidden': json['is_hidden'],
    };
}

export function HideOrRestoreReviewRequestToJSON(json: any): HideOrRestoreReviewRequest {
    return HideOrRestoreReviewRequestToJSONTyped(json, false);
}

export function HideOrRestoreReviewRequestToJSONTyped(value?: HideOrRestoreReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_hidden': value['isHidden'],
    };
}

