/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseReviewBookItem } from './BaseReviewBookItem';
import {
    BaseReviewBookItemFromJSON,
    BaseReviewBookItemFromJSONTyped,
    BaseReviewBookItemToJSON,
    BaseReviewBookItemToJSONTyped,
} from './BaseReviewBookItem';

/**
 * 
 * @export
 * @interface HideOrRestoreReviewResponse
 */
export interface HideOrRestoreReviewResponse {
    /**
     * 
     * @type {string}
     * @memberof HideOrRestoreReviewResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof HideOrRestoreReviewResponse
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof HideOrRestoreReviewResponse
     */
    userId: string | null;
    /**
     * 
     * @type {string}
     * @memberof HideOrRestoreReviewResponse
     */
    orderItemId: string;
    /**
     * 
     * @type {number}
     * @memberof HideOrRestoreReviewResponse
     */
    rating: number | null;
    /**
     * 
     * @type {string}
     * @memberof HideOrRestoreReviewResponse
     */
    comment: string | null;
    /**
     * 
     * @type {Date}
     * @memberof HideOrRestoreReviewResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof HideOrRestoreReviewResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof HideOrRestoreReviewResponse
     */
    isHidden: boolean;
    /**
     * 
     * @type {Date}
     * @memberof HideOrRestoreReviewResponse
     */
    hiddenAt: Date | null;
    /**
     * 
     * @type {BaseReviewBookItem}
     * @memberof HideOrRestoreReviewResponse
     */
    book: BaseReviewBookItem;
}

/**
 * Check if a given object implements the HideOrRestoreReviewResponse interface.
 */
export function instanceOfHideOrRestoreReviewResponse(value: object): value is HideOrRestoreReviewResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('orderItemId' in value) || value['orderItemId'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('isHidden' in value) || value['isHidden'] === undefined) return false;
    if (!('hiddenAt' in value) || value['hiddenAt'] === undefined) return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    return true;
}

export function HideOrRestoreReviewResponseFromJSON(json: any): HideOrRestoreReviewResponse {
    return HideOrRestoreReviewResponseFromJSONTyped(json, false);
}

export function HideOrRestoreReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HideOrRestoreReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bookId': json['book_id'],
        'userId': json['user_id'],
        'orderItemId': json['order_item_id'],
        'rating': json['rating'],
        'comment': json['comment'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'isHidden': json['is_hidden'],
        'hiddenAt': (json['hidden_at'] == null ? null : new Date(json['hidden_at'])),
        'book': BaseReviewBookItemFromJSON(json['book']),
    };
}

export function HideOrRestoreReviewResponseToJSON(json: any): HideOrRestoreReviewResponse {
    return HideOrRestoreReviewResponseToJSONTyped(json, false);
}

export function HideOrRestoreReviewResponseToJSONTyped(value?: HideOrRestoreReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'book_id': value['bookId'],
        'user_id': value['userId'],
        'order_item_id': value['orderItemId'],
        'rating': value['rating'],
        'comment': value['comment'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
        'is_hidden': value['isHidden'],
        'hidden_at': (value['hiddenAt'] == null ? null : (value['hiddenAt'] as any).toISOString()),
        'book': BaseReviewBookItemToJSON(value['book']),
    };
}

