/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkAllNotificationsAsReadResponse
 */
export interface MarkAllNotificationsAsReadResponse {
    /**
     * 
     * @type {number}
     * @memberof MarkAllNotificationsAsReadResponse
     */
    markedCount: number;
}

/**
 * Check if a given object implements the MarkAllNotificationsAsReadResponse interface.
 */
export function instanceOfMarkAllNotificationsAsReadResponse(value: object): value is MarkAllNotificationsAsReadResponse {
    if (!('markedCount' in value) || value['markedCount'] === undefined) return false;
    return true;
}

export function MarkAllNotificationsAsReadResponseFromJSON(json: any): MarkAllNotificationsAsReadResponse {
    return MarkAllNotificationsAsReadResponseFromJSONTyped(json, false);
}

export function MarkAllNotificationsAsReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkAllNotificationsAsReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'markedCount': json['marked_count'],
    };
}

export function MarkAllNotificationsAsReadResponseToJSON(json: any): MarkAllNotificationsAsReadResponse {
    return MarkAllNotificationsAsReadResponseToJSONTyped(json, false);
}

export function MarkAllNotificationsAsReadResponseToJSONTyped(value?: MarkAllNotificationsAsReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'marked_count': value['markedCount'],
    };
}

