/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkNotificationAsReadResponse
 */
export interface MarkNotificationAsReadResponse {
    /**
     * 
     * @type {string}
     * @memberof MarkNotificationAsReadResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof MarkNotificationAsReadResponse
     */
    userId: string | null;
    /**
     * 
     * @type {string}
     * @memberof MarkNotificationAsReadResponse
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof MarkNotificationAsReadResponse
     */
    subject: string;
    /**
     * 
     * @type {string}
     * @memberof MarkNotificationAsReadResponse
     */
    body: string;
    /**
     * 
     * @type {boolean}
     * @memberof MarkNotificationAsReadResponse
     */
    isRead: boolean;
    /**
     * 
     * @type {Date}
     * @memberof MarkNotificationAsReadResponse
     */
    readAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof MarkNotificationAsReadResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the MarkNotificationAsReadResponse interface.
 */
export function instanceOfMarkNotificationAsReadResponse(value: object): value is MarkNotificationAsReadResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('isRead' in value) || value['isRead'] === undefined) return false;
    if (!('readAt' in value) || value['readAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function MarkNotificationAsReadResponseFromJSON(json: any): MarkNotificationAsReadResponse {
    return MarkNotificationAsReadResponseFromJSONTyped(json, false);
}

export function MarkNotificationAsReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkNotificationAsReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['user_id'],
        'type': json['type'],
        'subject': json['subject'],
        'body': json['body'],
        'isRead': json['is_read'],
        'readAt': (json['read_at'] == null ? null : new Date(json['read_at'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function MarkNotificationAsReadResponseToJSON(json: any): MarkNotificationAsReadResponse {
    return MarkNotificationAsReadResponseToJSONTyped(json, false);
}

export function MarkNotificationAsReadResponseToJSONTyped(value?: MarkNotificationAsReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'type': value['type'],
        'subject': value['subject'],
        'body': value['body'],
        'is_read': value['isRead'],
        'read_at': (value['readAt'] == null ? null : (value['readAt'] as any).toISOString()),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

