/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthLoginUrlResponse
 */
export interface OAuthLoginUrlResponse {
    /**
     * OAuth provider authorization URL; redirect the browser to this URL
     * @type {string}
     * @memberof OAuthLoginUrlResponse
     */
    url: string;
}

/**
 * Check if a given object implements the OAuthLoginUrlResponse interface.
 */
export function instanceOfOAuthLoginUrlResponse(value: object): value is OAuthLoginUrlResponse {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function OAuthLoginUrlResponseFromJSON(json: any): OAuthLoginUrlResponse {
    return OAuthLoginUrlResponseFromJSONTyped(json, false);
}

export function OAuthLoginUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthLoginUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function OAuthLoginUrlResponseToJSON(json: any): OAuthLoginUrlResponse {
    return OAuthLoginUrlResponseToJSONTyped(json, false);
}

export function OAuthLoginUrlResponseToJSONTyped(value?: OAuthLoginUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

