/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OnlineBankingPaymentRequest
 */
export interface OnlineBankingPaymentRequest {
    /**
     * 
     * @type {string}
     * @memberof OnlineBankingPaymentRequest
     */
    paymentMethod: OnlineBankingPaymentRequestPaymentMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof OnlineBankingPaymentRequest
     */
    outcome: OnlineBankingPaymentRequestOutcomeEnum;
    /**
     * 
     * @type {string}
     * @memberof OnlineBankingPaymentRequest
     */
    bankName: string;
    /**
     * 
     * @type {string}
     * @memberof OnlineBankingPaymentRequest
     */
    accountNumber: string;
}

/**
* @export
* @enum {string}
*/
export enum OnlineBankingPaymentRequestPaymentMethodEnum {
    ONLINE_BANKING = 'online_banking'
}
/**
* @export
* @enum {string}
*/
export enum OnlineBankingPaymentRequestOutcomeEnum {
    SUCCESS = 'success',
    FAILURE = 'failure'
}


/**
 * Check if a given object implements the OnlineBankingPaymentRequest interface.
 */
export function instanceOfOnlineBankingPaymentRequest(value: object): value is OnlineBankingPaymentRequest {
    if (!('paymentMethod' in value) || value['paymentMethod'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('bankName' in value) || value['bankName'] === undefined) return false;
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    return true;
}

export function OnlineBankingPaymentRequestFromJSON(json: any): OnlineBankingPaymentRequest {
    return OnlineBankingPaymentRequestFromJSONTyped(json, false);
}

export function OnlineBankingPaymentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OnlineBankingPaymentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentMethod': json['payment_method'],
        'outcome': json['outcome'],
        'bankName': json['bank_name'],
        'accountNumber': json['account_number'],
    };
}

export function OnlineBankingPaymentRequestToJSON(json: any): OnlineBankingPaymentRequest {
    return OnlineBankingPaymentRequestToJSONTyped(json, false);
}

export function OnlineBankingPaymentRequestToJSONTyped(value?: OnlineBankingPaymentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'payment_method': value['paymentMethod'],
        'outcome': value['outcome'],
        'bank_name': value['bankName'],
        'account_number': value['accountNumber'],
    };
}

