/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum OrderStatus {
    PENDING = 'pending',
    PAID = 'paid',
    SHIPPED = 'shipped',
    DELIVERED = 'delivered',
    CANCELLED = 'cancelled'
}


export function instanceOfOrderStatus(value: any): boolean {
    for (const key in OrderStatus) {
        if (Object.prototype.hasOwnProperty.call(OrderStatus, key)) {
            if (OrderStatus[key as keyof typeof OrderStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OrderStatusFromJSON(json: any): OrderStatus {
    return OrderStatusFromJSONTyped(json, false);
}

export function OrderStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderStatus {
    return json as OrderStatus;
}

export function OrderStatusToJSON(value?: OrderStatus | null): any {
    return value as any;
}

export function OrderStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): OrderStatus {
    return value as OrderStatus;
}

