/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseBookResponse } from './BaseBookResponse';
import {
    BaseBookResponseFromJSON,
    BaseBookResponseFromJSONTyped,
    BaseBookResponseToJSON,
    BaseBookResponseToJSONTyped,
} from './BaseBookResponse';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface PaginatedResponseBaseBookResponse
 */
export interface PaginatedResponseBaseBookResponse {
    /**
     * 
     * @type {Array<BaseBookResponse>}
     * @memberof PaginatedResponseBaseBookResponse
     */
    items: Array<BaseBookResponse>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedResponseBaseBookResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResponseBaseBookResponse interface.
 */
export function instanceOfPaginatedResponseBaseBookResponse(value: object): value is PaginatedResponseBaseBookResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedResponseBaseBookResponseFromJSON(json: any): PaginatedResponseBaseBookResponse {
    return PaginatedResponseBaseBookResponseFromJSONTyped(json, false);
}

export function PaginatedResponseBaseBookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseBaseBookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BaseBookResponseFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginatedResponseBaseBookResponseToJSON(json: any): PaginatedResponseBaseBookResponse {
    return PaginatedResponseBaseBookResponseToJSONTyped(json, false);
}

export function PaginatedResponseBaseBookResponseToJSONTyped(value?: PaginatedResponseBaseBookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(BaseBookResponseToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

