/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderSummaryResponse } from './OrderSummaryResponse';
import {
    OrderSummaryResponseFromJSON,
    OrderSummaryResponseFromJSONTyped,
    OrderSummaryResponseToJSON,
    OrderSummaryResponseToJSONTyped,
} from './OrderSummaryResponse';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface PaginatedResponseOrderSummaryResponse
 */
export interface PaginatedResponseOrderSummaryResponse {
    /**
     * 
     * @type {Array<OrderSummaryResponse>}
     * @memberof PaginatedResponseOrderSummaryResponse
     */
    items: Array<OrderSummaryResponse>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedResponseOrderSummaryResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResponseOrderSummaryResponse interface.
 */
export function instanceOfPaginatedResponseOrderSummaryResponse(value: object): value is PaginatedResponseOrderSummaryResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedResponseOrderSummaryResponseFromJSON(json: any): PaginatedResponseOrderSummaryResponse {
    return PaginatedResponseOrderSummaryResponseFromJSONTyped(json, false);
}

export function PaginatedResponseOrderSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseOrderSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(OrderSummaryResponseFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginatedResponseOrderSummaryResponseToJSON(json: any): PaginatedResponseOrderSummaryResponse {
    return PaginatedResponseOrderSummaryResponseToJSONTyped(json, false);
}

export function PaginatedResponseOrderSummaryResponseToJSONTyped(value?: PaginatedResponseOrderSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(OrderSummaryResponseToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

