/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { BasePublisherResponse } from './BasePublisherResponse';
import {
    BasePublisherResponseFromJSON,
    BasePublisherResponseFromJSONTyped,
    BasePublisherResponseToJSON,
    BasePublisherResponseToJSONTyped,
} from './BasePublisherResponse';

/**
 * 
 * @export
 * @interface PaginatedResponseBasePublisherResponse
 */
export interface PaginatedResponseBasePublisherResponse {
    /**
     * 
     * @type {Array<BasePublisherResponse>}
     * @memberof PaginatedResponseBasePublisherResponse
     */
    items: Array<BasePublisherResponse>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedResponseBasePublisherResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResponseBasePublisherResponse interface.
 */
export function instanceOfPaginatedResponseBasePublisherResponse(value: object): value is PaginatedResponseBasePublisherResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedResponseBasePublisherResponseFromJSON(json: any): PaginatedResponseBasePublisherResponse {
    return PaginatedResponseBasePublisherResponseFromJSONTyped(json, false);
}

export function PaginatedResponseBasePublisherResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseBasePublisherResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(BasePublisherResponseFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginatedResponseBasePublisherResponseToJSON(json: any): PaginatedResponseBasePublisherResponse {
    return PaginatedResponseBasePublisherResponseToJSONTyped(json, false);
}

export function PaginatedResponseBasePublisherResponseToJSONTyped(value?: PaginatedResponseBasePublisherResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(BasePublisherResponseToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

