/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { PublicReviewItemResponse } from './PublicReviewItemResponse';
import {
    PublicReviewItemResponseFromJSON,
    PublicReviewItemResponseFromJSONTyped,
    PublicReviewItemResponseToJSON,
    PublicReviewItemResponseToJSONTyped,
} from './PublicReviewItemResponse';

/**
 * 
 * @export
 * @interface PaginatedResponsePublicReviewItemResponse
 */
export interface PaginatedResponsePublicReviewItemResponse {
    /**
     * 
     * @type {Array<PublicReviewItemResponse>}
     * @memberof PaginatedResponsePublicReviewItemResponse
     */
    items: Array<PublicReviewItemResponse>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedResponsePublicReviewItemResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResponsePublicReviewItemResponse interface.
 */
export function instanceOfPaginatedResponsePublicReviewItemResponse(value: object): value is PaginatedResponsePublicReviewItemResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedResponsePublicReviewItemResponseFromJSON(json: any): PaginatedResponsePublicReviewItemResponse {
    return PaginatedResponsePublicReviewItemResponseFromJSONTyped(json, false);
}

export function PaginatedResponsePublicReviewItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponsePublicReviewItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PublicReviewItemResponseFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginatedResponsePublicReviewItemResponseToJSON(json: any): PaginatedResponsePublicReviewItemResponse {
    return PaginatedResponsePublicReviewItemResponseToJSONTyped(json, false);
}

export function PaginatedResponsePublicReviewItemResponseToJSONTyped(value?: PaginatedResponsePublicReviewItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PublicReviewItemResponseToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

