/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';
import type { ReportJobListItemResponse } from './ReportJobListItemResponse';
import {
    ReportJobListItemResponseFromJSON,
    ReportJobListItemResponseFromJSONTyped,
    ReportJobListItemResponseToJSON,
    ReportJobListItemResponseToJSONTyped,
} from './ReportJobListItemResponse';

/**
 * 
 * @export
 * @interface PaginatedResponseReportJobListItemResponse
 */
export interface PaginatedResponseReportJobListItemResponse {
    /**
     * 
     * @type {Array<ReportJobListItemResponse>}
     * @memberof PaginatedResponseReportJobListItemResponse
     */
    items: Array<ReportJobListItemResponse>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedResponseReportJobListItemResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResponseReportJobListItemResponse interface.
 */
export function instanceOfPaginatedResponseReportJobListItemResponse(value: object): value is PaginatedResponseReportJobListItemResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedResponseReportJobListItemResponseFromJSON(json: any): PaginatedResponseReportJobListItemResponse {
    return PaginatedResponseReportJobListItemResponseFromJSONTyped(json, false);
}

export function PaginatedResponseReportJobListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseReportJobListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ReportJobListItemResponseFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginatedResponseReportJobListItemResponseToJSON(json: any): PaginatedResponseReportJobListItemResponse {
    return PaginatedResponseReportJobListItemResponseToJSONTyped(json, false);
}

export function PaginatedResponseReportJobListItemResponseToJSONTyped(value?: PaginatedResponseReportJobListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ReportJobListItemResponseToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

