/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserListItemResponse } from './UserListItemResponse';
import {
    UserListItemResponseFromJSON,
    UserListItemResponseFromJSONTyped,
    UserListItemResponseToJSON,
    UserListItemResponseToJSONTyped,
} from './UserListItemResponse';
import type { PaginationMeta } from './PaginationMeta';
import {
    PaginationMetaFromJSON,
    PaginationMetaFromJSONTyped,
    PaginationMetaToJSON,
    PaginationMetaToJSONTyped,
} from './PaginationMeta';

/**
 * 
 * @export
 * @interface PaginatedResponseUserListItemResponse
 */
export interface PaginatedResponseUserListItemResponse {
    /**
     * 
     * @type {Array<UserListItemResponse>}
     * @memberof PaginatedResponseUserListItemResponse
     */
    items: Array<UserListItemResponse>;
    /**
     * 
     * @type {PaginationMeta}
     * @memberof PaginatedResponseUserListItemResponse
     */
    pagination: PaginationMeta;
}

/**
 * Check if a given object implements the PaginatedResponseUserListItemResponse interface.
 */
export function instanceOfPaginatedResponseUserListItemResponse(value: object): value is PaginatedResponseUserListItemResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function PaginatedResponseUserListItemResponseFromJSON(json: any): PaginatedResponseUserListItemResponse {
    return PaginatedResponseUserListItemResponseFromJSONTyped(json, false);
}

export function PaginatedResponseUserListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseUserListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(UserListItemResponseFromJSON)),
        'pagination': PaginationMetaFromJSON(json['pagination']),
    };
}

export function PaginatedResponseUserListItemResponseToJSON(json: any): PaginatedResponseUserListItemResponse {
    return PaginatedResponseUserListItemResponseToJSONTyped(json, false);
}

export function PaginatedResponseUserListItemResponseToJSONTyped(value?: PaginatedResponseUserListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(UserListItemResponseToJSON)),
        'pagination': PaginationMetaToJSON(value['pagination']),
    };
}

