/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceOrderRequest
 */
export interface PlaceOrderRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof PlaceOrderRequest
     */
    cartItemIds: Array<string>;
}

/**
 * Check if a given object implements the PlaceOrderRequest interface.
 */
export function instanceOfPlaceOrderRequest(value: object): value is PlaceOrderRequest {
    if (!('cartItemIds' in value) || value['cartItemIds'] === undefined) return false;
    return true;
}

export function PlaceOrderRequestFromJSON(json: any): PlaceOrderRequest {
    return PlaceOrderRequestFromJSONTyped(json, false);
}

export function PlaceOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'cartItemIds': json['cart_item_ids'],
    };
}

export function PlaceOrderRequestToJSON(json: any): PlaceOrderRequest {
    return PlaceOrderRequestToJSONTyped(json, false);
}

export function PlaceOrderRequestToJSONTyped(value?: PlaceOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cart_item_ids': value['cartItemIds'],
    };
}

