/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceMax
 */
export interface PriceMax {
}

/**
 * Check if a given object implements the PriceMax interface.
 */
export function instanceOfPriceMax(value: object): value is PriceMax {
    return true;
}

export function PriceMaxFromJSON(json: any): PriceMax {
    return PriceMaxFromJSONTyped(json, false);
}

export function PriceMaxFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceMax {
    return json;
}

export function PriceMaxToJSON(json: any): PriceMax {
    return PriceMaxToJSONTyped(json, false);
}

export function PriceMaxToJSONTyped(value?: PriceMax | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

