/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Price1
 */
export interface Price1 {
}

/**
 * Check if a given object implements the Price1 interface.
 */
export function instanceOfPrice1(value: object): value is Price1 {
    return true;
}

export function Price1FromJSON(json: any): Price1 {
    return Price1FromJSONTyped(json, false);
}

export function Price1FromJSONTyped(json: any, ignoreDiscriminator: boolean): Price1 {
    return json;
}

export function Price1ToJSON(json: any): Price1 {
    return Price1ToJSONTyped(json, false);
}

export function Price1ToJSONTyped(value?: Price1 | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

