/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterAdminRequest
 */
export interface RegisterAdminRequest {
    /**
     * Admin account email address
     * @type {string}
     * @memberof RegisterAdminRequest
     */
    email: string;
    /**
     * Plain-text password (hashed server-side)
     * @type {string}
     * @memberof RegisterAdminRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAdminRequest
     */
    fullName: string;
    /**
     * 
     * @type {Date}
     * @memberof RegisterAdminRequest
     */
    dateOfBirth?: Date | null;
}

/**
 * Check if a given object implements the RegisterAdminRequest interface.
 */
export function instanceOfRegisterAdminRequest(value: object): value is RegisterAdminRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    return true;
}

export function RegisterAdminRequestFromJSON(json: any): RegisterAdminRequest {
    return RegisterAdminRequestFromJSONTyped(json, false);
}

export function RegisterAdminRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterAdminRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'fullName': json['full_name'],
        'dateOfBirth': json['date_of_birth'] == null ? undefined : (new Date(json['date_of_birth'])),
    };
}

export function RegisterAdminRequestToJSON(json: any): RegisterAdminRequest {
    return RegisterAdminRequestToJSONTyped(json, false);
}

export function RegisterAdminRequestToJSONTyped(value?: RegisterAdminRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'full_name': value['fullName'],
        'date_of_birth': value['dateOfBirth'] == null ? undefined : ((value['dateOfBirth'] as any).toISOString().substring(0,10)),
    };
}

