/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserStatus } from './UserStatus';
import {
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserStatusToJSONTyped,
} from './UserStatus';

/**
 * 
 * @export
 * @interface RegisterResponse
 */
export interface RegisterResponse {
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    fullName: string;
    /**
     * 
     * @type {UserStatus}
     * @memberof RegisterResponse
     */
    status: UserStatus;
    /**
     * 
     * @type {Date}
     * @memberof RegisterResponse
     */
    createdAt: Date;
}



/**
 * Check if a given object implements the RegisterResponse interface.
 */
export function instanceOfRegisterResponse(value: object): value is RegisterResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RegisterResponseFromJSON(json: any): RegisterResponse {
    return RegisterResponseFromJSONTyped(json, false);
}

export function RegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'fullName': json['full_name'],
        'status': UserStatusFromJSON(json['status']),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function RegisterResponseToJSON(json: any): RegisterResponse {
    return RegisterResponseToJSONTyped(json, false);
}

export function RegisterResponseToJSONTyped(value?: RegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'full_name': value['fullName'],
        'status': UserStatusToJSON(value['status']),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

