/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterCustomerRequest
 */
export interface RegisterCustomerRequest {
    /**
     * User email address
     * @type {string}
     * @memberof RegisterCustomerRequest
     */
    email: string;
    /**
     * User password (plain text, will be hashed server-side)
     * @type {string}
     * @memberof RegisterCustomerRequest
     */
    password: string;
    /**
     * Confirmed password
     * @type {string}
     * @memberof RegisterCustomerRequest
     */
    confirmPassword: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterCustomerRequest
     */
    fullName: string;
    /**
     * ISO 8601 date (YYYY-MM-DD)
     * @type {Date}
     * @memberof RegisterCustomerRequest
     */
    dateOfBirth: Date;
}

/**
 * Check if a given object implements the RegisterCustomerRequest interface.
 */
export function instanceOfRegisterCustomerRequest(value: object): value is RegisterCustomerRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('confirmPassword' in value) || value['confirmPassword'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false;
    return true;
}

export function RegisterCustomerRequestFromJSON(json: any): RegisterCustomerRequest {
    return RegisterCustomerRequestFromJSONTyped(json, false);
}

export function RegisterCustomerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterCustomerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'confirmPassword': json['confirm_password'],
        'fullName': json['full_name'],
        'dateOfBirth': (new Date(json['date_of_birth'])),
    };
}

export function RegisterCustomerRequestToJSON(json: any): RegisterCustomerRequest {
    return RegisterCustomerRequestToJSONTyped(json, false);
}

export function RegisterCustomerRequestToJSONTyped(value?: RegisterCustomerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'confirm_password': value['confirmPassword'],
        'full_name': value['fullName'],
        'date_of_birth': ((value['dateOfBirth']).toISOString().substring(0,10)),
    };
}

