/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ReportJobStatus {
    PENDING = 'pending',
    PROCESSING = 'processing',
    COMPLETED = 'completed',
    FAILED = 'failed'
}


export function instanceOfReportJobStatus(value: any): boolean {
    for (const key in ReportJobStatus) {
        if (Object.prototype.hasOwnProperty.call(ReportJobStatus, key)) {
            if (ReportJobStatus[key as keyof typeof ReportJobStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ReportJobStatusFromJSON(json: any): ReportJobStatus {
    return ReportJobStatusFromJSONTyped(json, false);
}

export function ReportJobStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportJobStatus {
    return json as ReportJobStatus;
}

export function ReportJobStatusToJSON(value?: ReportJobStatus | null): any {
    return value as any;
}

export function ReportJobStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ReportJobStatus {
    return value as ReportJobStatus;
}

