/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportFormat } from './ReportFormat';
import {
    ReportFormatFromJSON,
    ReportFormatFromJSONTyped,
    ReportFormatToJSON,
    ReportFormatToJSONTyped,
} from './ReportFormat';
import type { ReportJobStatus } from './ReportJobStatus';
import {
    ReportJobStatusFromJSON,
    ReportJobStatusFromJSONTyped,
    ReportJobStatusToJSON,
    ReportJobStatusToJSONTyped,
} from './ReportJobStatus';
import type { ReportType } from './ReportType';
import {
    ReportTypeFromJSON,
    ReportTypeFromJSONTyped,
    ReportTypeToJSON,
    ReportTypeToJSONTyped,
} from './ReportType';

/**
 * 
 * @export
 * @interface ReportJobListItemResponse
 */
export interface ReportJobListItemResponse {
    /**
     * 
     * @type {string}
     * @memberof ReportJobListItemResponse
     */
    jobId: string;
    /**
     * 
     * @type {ReportType}
     * @memberof ReportJobListItemResponse
     */
    type: ReportType;
    /**
     * 
     * @type {Date}
     * @memberof ReportJobListItemResponse
     */
    dateFrom: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReportJobListItemResponse
     */
    dateTo: Date;
    /**
     * 
     * @type {ReportFormat}
     * @memberof ReportJobListItemResponse
     */
    format: ReportFormat;
    /**
     * 
     * @type {number}
     * @memberof ReportJobListItemResponse
     */
    limit: number | null;
    /**
     * 
     * @type {ReportJobStatus}
     * @memberof ReportJobListItemResponse
     */
    status: ReportJobStatus;
    /**
     * 
     * @type {Date}
     * @memberof ReportJobListItemResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReportJobListItemResponse
     */
    completedAt: Date | null;
}



/**
 * Check if a given object implements the ReportJobListItemResponse interface.
 */
export function instanceOfReportJobListItemResponse(value: object): value is ReportJobListItemResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('dateFrom' in value) || value['dateFrom'] === undefined) return false;
    if (!('dateTo' in value) || value['dateTo'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    return true;
}

export function ReportJobListItemResponseFromJSON(json: any): ReportJobListItemResponse {
    return ReportJobListItemResponseFromJSONTyped(json, false);
}

export function ReportJobListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportJobListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'type': ReportTypeFromJSON(json['type']),
        'dateFrom': (new Date(json['date_from'])),
        'dateTo': (new Date(json['date_to'])),
        'format': ReportFormatFromJSON(json['format']),
        'limit': json['limit'],
        'status': ReportJobStatusFromJSON(json['status']),
        'createdAt': (new Date(json['created_at'])),
        'completedAt': (json['completed_at'] == null ? null : new Date(json['completed_at'])),
    };
}

export function ReportJobListItemResponseToJSON(json: any): ReportJobListItemResponse {
    return ReportJobListItemResponseToJSONTyped(json, false);
}

export function ReportJobListItemResponseToJSONTyped(value?: ReportJobListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'type': ReportTypeToJSON(value['type']),
        'date_from': ((value['dateFrom']).toISOString().substring(0,10)),
        'date_to': ((value['dateTo']).toISOString().substring(0,10)),
        'format': ReportFormatToJSON(value['format']),
        'limit': value['limit'],
        'status': ReportJobStatusToJSON(value['status']),
        'created_at': ((value['createdAt']).toISOString()),
        'completed_at': (value['completedAt'] == null ? null : (value['completedAt'] as any).toISOString()),
    };
}

