/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendVerificationResponse
 */
export interface ResendVerificationResponse {
    /**
     * 
     * @type {string}
     * @memberof ResendVerificationResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ResendVerificationResponse
     */
    message: string;
}

/**
 * Check if a given object implements the ResendVerificationResponse interface.
 */
export function instanceOfResendVerificationResponse(value: object): value is ResendVerificationResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ResendVerificationResponseFromJSON(json: any): ResendVerificationResponse {
    return ResendVerificationResponseFromJSONTyped(json, false);
}

export function ResendVerificationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendVerificationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'message': json['message'],
    };
}

export function ResendVerificationResponseToJSON(json: any): ResendVerificationResponse {
    return ResendVerificationResponseToJSONTyped(json, false);
}

export function ResendVerificationResponseToJSONTyped(value?: ResendVerificationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'message': value['message'],
    };
}

