/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { ClearAllCartItemsResponse } from './ClearAllCartItemsResponse';
import {
    ClearAllCartItemsResponseFromJSON,
    ClearAllCartItemsResponseFromJSONTyped,
    ClearAllCartItemsResponseToJSON,
    ClearAllCartItemsResponseToJSONTyped,
} from './ClearAllCartItemsResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperClearAllCartItemsResponse
 */
export interface ResponseWrapperClearAllCartItemsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperClearAllCartItemsResponse
     */
    success: boolean;
    /**
     * 
     * @type {ClearAllCartItemsResponse}
     * @memberof ResponseWrapperClearAllCartItemsResponse
     */
    data: ClearAllCartItemsResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperClearAllCartItemsResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperClearAllCartItemsResponse interface.
 */
export function instanceOfResponseWrapperClearAllCartItemsResponse(value: object): value is ResponseWrapperClearAllCartItemsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperClearAllCartItemsResponseFromJSON(json: any): ResponseWrapperClearAllCartItemsResponse {
    return ResponseWrapperClearAllCartItemsResponseFromJSONTyped(json, false);
}

export function ResponseWrapperClearAllCartItemsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperClearAllCartItemsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ClearAllCartItemsResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperClearAllCartItemsResponseToJSON(json: any): ResponseWrapperClearAllCartItemsResponse {
    return ResponseWrapperClearAllCartItemsResponseToJSONTyped(json, false);
}

export function ResponseWrapperClearAllCartItemsResponseToJSONTyped(value?: ResponseWrapperClearAllCartItemsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ClearAllCartItemsResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

