/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LogoutResponse } from './LogoutResponse';
import {
    LogoutResponseFromJSON,
    LogoutResponseFromJSONTyped,
    LogoutResponseToJSON,
    LogoutResponseToJSONTyped,
} from './LogoutResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperLogoutResponse
 */
export interface ResponseWrapperLogoutResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperLogoutResponse
     */
    success: boolean;
    /**
     * 
     * @type {LogoutResponse}
     * @memberof ResponseWrapperLogoutResponse
     */
    data: LogoutResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperLogoutResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperLogoutResponse interface.
 */
export function instanceOfResponseWrapperLogoutResponse(value: object): value is ResponseWrapperLogoutResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperLogoutResponseFromJSON(json: any): ResponseWrapperLogoutResponse {
    return ResponseWrapperLogoutResponseFromJSONTyped(json, false);
}

export function ResponseWrapperLogoutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperLogoutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': LogoutResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperLogoutResponseToJSON(json: any): ResponseWrapperLogoutResponse {
    return ResponseWrapperLogoutResponseToJSONTyped(json, false);
}

export function ResponseWrapperLogoutResponseToJSONTyped(value?: ResponseWrapperLogoutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': LogoutResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

