/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { UpdateMyReviewResponse } from './UpdateMyReviewResponse';
import {
    UpdateMyReviewResponseFromJSON,
    UpdateMyReviewResponseFromJSONTyped,
    UpdateMyReviewResponseToJSON,
    UpdateMyReviewResponseToJSONTyped,
} from './UpdateMyReviewResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperUpdateMyReviewResponse
 */
export interface ResponseWrapperUpdateMyReviewResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperUpdateMyReviewResponse
     */
    success: boolean;
    /**
     * 
     * @type {UpdateMyReviewResponse}
     * @memberof ResponseWrapperUpdateMyReviewResponse
     */
    data: UpdateMyReviewResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperUpdateMyReviewResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperUpdateMyReviewResponse interface.
 */
export function instanceOfResponseWrapperUpdateMyReviewResponse(value: object): value is ResponseWrapperUpdateMyReviewResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperUpdateMyReviewResponseFromJSON(json: any): ResponseWrapperUpdateMyReviewResponse {
    return ResponseWrapperUpdateMyReviewResponseFromJSONTyped(json, false);
}

export function ResponseWrapperUpdateMyReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperUpdateMyReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': UpdateMyReviewResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperUpdateMyReviewResponseToJSON(json: any): ResponseWrapperUpdateMyReviewResponse {
    return ResponseWrapperUpdateMyReviewResponseToJSONTyped(json, false);
}

export function ResponseWrapperUpdateMyReviewResponseToJSONTyped(value?: ResponseWrapperUpdateMyReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': UpdateMyReviewResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

