/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { MoveWishlistItemToCartResponse } from './MoveWishlistItemToCartResponse';
import {
    MoveWishlistItemToCartResponseFromJSON,
    MoveWishlistItemToCartResponseFromJSONTyped,
    MoveWishlistItemToCartResponseToJSON,
    MoveWishlistItemToCartResponseToJSONTyped,
} from './MoveWishlistItemToCartResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperMoveWishlistItemToCartResponse
 */
export interface ResponseWrapperMoveWishlistItemToCartResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperMoveWishlistItemToCartResponse
     */
    success: boolean;
    /**
     * 
     * @type {MoveWishlistItemToCartResponse}
     * @memberof ResponseWrapperMoveWishlistItemToCartResponse
     */
    data: MoveWishlistItemToCartResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperMoveWishlistItemToCartResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperMoveWishlistItemToCartResponse interface.
 */
export function instanceOfResponseWrapperMoveWishlistItemToCartResponse(value: object): value is ResponseWrapperMoveWishlistItemToCartResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperMoveWishlistItemToCartResponseFromJSON(json: any): ResponseWrapperMoveWishlistItemToCartResponse {
    return ResponseWrapperMoveWishlistItemToCartResponseFromJSONTyped(json, false);
}

export function ResponseWrapperMoveWishlistItemToCartResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperMoveWishlistItemToCartResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': MoveWishlistItemToCartResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperMoveWishlistItemToCartResponseToJSON(json: any): ResponseWrapperMoveWishlistItemToCartResponse {
    return ResponseWrapperMoveWishlistItemToCartResponseToJSONTyped(json, false);
}

export function ResponseWrapperMoveWishlistItemToCartResponseToJSONTyped(value?: ResponseWrapperMoveWishlistItemToCartResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': MoveWishlistItemToCartResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

