/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerifyEmailResponse } from './VerifyEmailResponse';
import {
    VerifyEmailResponseFromJSON,
    VerifyEmailResponseFromJSONTyped,
    VerifyEmailResponseToJSON,
    VerifyEmailResponseToJSONTyped,
} from './VerifyEmailResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperVerifyEmailResponse
 */
export interface ResponseWrapperVerifyEmailResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperVerifyEmailResponse
     */
    success: boolean;
    /**
     * 
     * @type {VerifyEmailResponse}
     * @memberof ResponseWrapperVerifyEmailResponse
     */
    data: VerifyEmailResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperVerifyEmailResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperVerifyEmailResponse interface.
 */
export function instanceOfResponseWrapperVerifyEmailResponse(value: object): value is ResponseWrapperVerifyEmailResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperVerifyEmailResponseFromJSON(json: any): ResponseWrapperVerifyEmailResponse {
    return ResponseWrapperVerifyEmailResponseFromJSONTyped(json, false);
}

export function ResponseWrapperVerifyEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperVerifyEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': VerifyEmailResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperVerifyEmailResponseToJSON(json: any): ResponseWrapperVerifyEmailResponse {
    return ResponseWrapperVerifyEmailResponseToJSONTyped(json, false);
}

export function ResponseWrapperVerifyEmailResponseToJSONTyped(value?: ResponseWrapperVerifyEmailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': VerifyEmailResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

