/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewCategoryDetailResponse } from './ViewCategoryDetailResponse';
import {
    ViewCategoryDetailResponseFromJSON,
    ViewCategoryDetailResponseFromJSONTyped,
    ViewCategoryDetailResponseToJSON,
    ViewCategoryDetailResponseToJSONTyped,
} from './ViewCategoryDetailResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperViewCategoryDetailResponse
 */
export interface ResponseWrapperViewCategoryDetailResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperViewCategoryDetailResponse
     */
    success: boolean;
    /**
     * 
     * @type {ViewCategoryDetailResponse}
     * @memberof ResponseWrapperViewCategoryDetailResponse
     */
    data: ViewCategoryDetailResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperViewCategoryDetailResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperViewCategoryDetailResponse interface.
 */
export function instanceOfResponseWrapperViewCategoryDetailResponse(value: object): value is ResponseWrapperViewCategoryDetailResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperViewCategoryDetailResponseFromJSON(json: any): ResponseWrapperViewCategoryDetailResponse {
    return ResponseWrapperViewCategoryDetailResponseFromJSONTyped(json, false);
}

export function ResponseWrapperViewCategoryDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperViewCategoryDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ViewCategoryDetailResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperViewCategoryDetailResponseToJSON(json: any): ResponseWrapperViewCategoryDetailResponse {
    return ResponseWrapperViewCategoryDetailResponseToJSONTyped(json, false);
}

export function ResponseWrapperViewCategoryDetailResponseToJSONTyped(value?: ResponseWrapperViewCategoryDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ViewCategoryDetailResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

