/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { AddWishlistItemResponse } from './AddWishlistItemResponse';
import {
    AddWishlistItemResponseFromJSON,
    AddWishlistItemResponseFromJSONTyped,
    AddWishlistItemResponseToJSON,
    AddWishlistItemResponseToJSONTyped,
} from './AddWishlistItemResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperAddWishlistItemResponse
 */
export interface ResponseWrapperAddWishlistItemResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperAddWishlistItemResponse
     */
    success: boolean;
    /**
     * 
     * @type {AddWishlistItemResponse}
     * @memberof ResponseWrapperAddWishlistItemResponse
     */
    data: AddWishlistItemResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperAddWishlistItemResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperAddWishlistItemResponse interface.
 */
export function instanceOfResponseWrapperAddWishlistItemResponse(value: object): value is ResponseWrapperAddWishlistItemResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperAddWishlistItemResponseFromJSON(json: any): ResponseWrapperAddWishlistItemResponse {
    return ResponseWrapperAddWishlistItemResponseFromJSONTyped(json, false);
}

export function ResponseWrapperAddWishlistItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperAddWishlistItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': AddWishlistItemResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperAddWishlistItemResponseToJSON(json: any): ResponseWrapperAddWishlistItemResponse {
    return ResponseWrapperAddWishlistItemResponseToJSONTyped(json, false);
}

export function ResponseWrapperAddWishlistItemResponseToJSONTyped(value?: ResponseWrapperAddWishlistItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': AddWishlistItemResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

