/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { ViewCollectionDetailResponse } from './ViewCollectionDetailResponse';
import {
    ViewCollectionDetailResponseFromJSON,
    ViewCollectionDetailResponseFromJSONTyped,
    ViewCollectionDetailResponseToJSON,
    ViewCollectionDetailResponseToJSONTyped,
} from './ViewCollectionDetailResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperViewCollectionDetailResponse
 */
export interface ResponseWrapperViewCollectionDetailResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperViewCollectionDetailResponse
     */
    success: boolean;
    /**
     * 
     * @type {ViewCollectionDetailResponse}
     * @memberof ResponseWrapperViewCollectionDetailResponse
     */
    data: ViewCollectionDetailResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperViewCollectionDetailResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperViewCollectionDetailResponse interface.
 */
export function instanceOfResponseWrapperViewCollectionDetailResponse(value: object): value is ResponseWrapperViewCollectionDetailResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperViewCollectionDetailResponseFromJSON(json: any): ResponseWrapperViewCollectionDetailResponse {
    return ResponseWrapperViewCollectionDetailResponseFromJSONTyped(json, false);
}

export function ResponseWrapperViewCollectionDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperViewCollectionDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ViewCollectionDetailResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperViewCollectionDetailResponseToJSON(json: any): ResponseWrapperViewCollectionDetailResponse {
    return ResponseWrapperViewCollectionDetailResponseToJSONTyped(json, false);
}

export function ResponseWrapperViewCollectionDetailResponseToJSONTyped(value?: ResponseWrapperViewCollectionDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ViewCollectionDetailResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

