/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenResponse } from './TokenResponse';
import {
    TokenResponseFromJSON,
    TokenResponseFromJSONTyped,
    TokenResponseToJSON,
    TokenResponseToJSONTyped,
} from './TokenResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperTokenResponse
 */
export interface ResponseWrapperTokenResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperTokenResponse
     */
    success: boolean;
    /**
     * 
     * @type {TokenResponse}
     * @memberof ResponseWrapperTokenResponse
     */
    data: TokenResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperTokenResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperTokenResponse interface.
 */
export function instanceOfResponseWrapperTokenResponse(value: object): value is ResponseWrapperTokenResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperTokenResponseFromJSON(json: any): ResponseWrapperTokenResponse {
    return ResponseWrapperTokenResponseFromJSONTyped(json, false);
}

export function ResponseWrapperTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': TokenResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperTokenResponseToJSON(json: any): ResponseWrapperTokenResponse {
    return ResponseWrapperTokenResponseToJSONTyped(json, false);
}

export function ResponseWrapperTokenResponseToJSONTyped(value?: ResponseWrapperTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': TokenResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

