/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { CancelOrderResponse } from './CancelOrderResponse';
import {
    CancelOrderResponseFromJSON,
    CancelOrderResponseFromJSONTyped,
    CancelOrderResponseToJSON,
    CancelOrderResponseToJSONTyped,
} from './CancelOrderResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperCancelOrderResponse
 */
export interface ResponseWrapperCancelOrderResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperCancelOrderResponse
     */
    success: boolean;
    /**
     * 
     * @type {CancelOrderResponse}
     * @memberof ResponseWrapperCancelOrderResponse
     */
    data: CancelOrderResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperCancelOrderResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperCancelOrderResponse interface.
 */
export function instanceOfResponseWrapperCancelOrderResponse(value: object): value is ResponseWrapperCancelOrderResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperCancelOrderResponseFromJSON(json: any): ResponseWrapperCancelOrderResponse {
    return ResponseWrapperCancelOrderResponseFromJSONTyped(json, false);
}

export function ResponseWrapperCancelOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperCancelOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CancelOrderResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperCancelOrderResponseToJSON(json: any): ResponseWrapperCancelOrderResponse {
    return ResponseWrapperCancelOrderResponseToJSONTyped(json, false);
}

export function ResponseWrapperCancelOrderResponseToJSONTyped(value?: ResponseWrapperCancelOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CancelOrderResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

