/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { MarkAllNotificationsAsReadResponse } from './MarkAllNotificationsAsReadResponse';
import {
    MarkAllNotificationsAsReadResponseFromJSON,
    MarkAllNotificationsAsReadResponseFromJSONTyped,
    MarkAllNotificationsAsReadResponseToJSON,
    MarkAllNotificationsAsReadResponseToJSONTyped,
} from './MarkAllNotificationsAsReadResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperMarkAllNotificationsAsReadResponse
 */
export interface ResponseWrapperMarkAllNotificationsAsReadResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperMarkAllNotificationsAsReadResponse
     */
    success: boolean;
    /**
     * 
     * @type {MarkAllNotificationsAsReadResponse}
     * @memberof ResponseWrapperMarkAllNotificationsAsReadResponse
     */
    data: MarkAllNotificationsAsReadResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperMarkAllNotificationsAsReadResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperMarkAllNotificationsAsReadResponse interface.
 */
export function instanceOfResponseWrapperMarkAllNotificationsAsReadResponse(value: object): value is ResponseWrapperMarkAllNotificationsAsReadResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperMarkAllNotificationsAsReadResponseFromJSON(json: any): ResponseWrapperMarkAllNotificationsAsReadResponse {
    return ResponseWrapperMarkAllNotificationsAsReadResponseFromJSONTyped(json, false);
}

export function ResponseWrapperMarkAllNotificationsAsReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperMarkAllNotificationsAsReadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': MarkAllNotificationsAsReadResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperMarkAllNotificationsAsReadResponseToJSON(json: any): ResponseWrapperMarkAllNotificationsAsReadResponse {
    return ResponseWrapperMarkAllNotificationsAsReadResponseToJSONTyped(json, false);
}

export function ResponseWrapperMarkAllNotificationsAsReadResponseToJSONTyped(value?: ResponseWrapperMarkAllNotificationsAsReadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': MarkAllNotificationsAsReadResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

