/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { AddressResponse } from './AddressResponse';
import {
    AddressResponseFromJSON,
    AddressResponseFromJSONTyped,
    AddressResponseToJSON,
    AddressResponseToJSONTyped,
} from './AddressResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperAddressResponse
 */
export interface ResponseWrapperAddressResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperAddressResponse
     */
    success: boolean;
    /**
     * 
     * @type {AddressResponse}
     * @memberof ResponseWrapperAddressResponse
     */
    data: AddressResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperAddressResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperAddressResponse interface.
 */
export function instanceOfResponseWrapperAddressResponse(value: object): value is ResponseWrapperAddressResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperAddressResponseFromJSON(json: any): ResponseWrapperAddressResponse {
    return ResponseWrapperAddressResponseFromJSONTyped(json, false);
}

export function ResponseWrapperAddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperAddressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': AddressResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperAddressResponseToJSON(json: any): ResponseWrapperAddressResponse {
    return ResponseWrapperAddressResponseToJSONTyped(json, false);
}

export function ResponseWrapperAddressResponseToJSONTyped(value?: ResponseWrapperAddressResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': AddressResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

