/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PayOrderResponse } from './PayOrderResponse';
import {
    PayOrderResponseFromJSON,
    PayOrderResponseFromJSONTyped,
    PayOrderResponseToJSON,
    PayOrderResponseToJSONTyped,
} from './PayOrderResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperPayOrderResponse
 */
export interface ResponseWrapperPayOrderResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperPayOrderResponse
     */
    success: boolean;
    /**
     * 
     * @type {PayOrderResponse}
     * @memberof ResponseWrapperPayOrderResponse
     */
    data: PayOrderResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperPayOrderResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperPayOrderResponse interface.
 */
export function instanceOfResponseWrapperPayOrderResponse(value: object): value is ResponseWrapperPayOrderResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperPayOrderResponseFromJSON(json: any): ResponseWrapperPayOrderResponse {
    return ResponseWrapperPayOrderResponseFromJSONTyped(json, false);
}

export function ResponseWrapperPayOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperPayOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PayOrderResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperPayOrderResponseToJSON(json: any): ResponseWrapperPayOrderResponse {
    return ResponseWrapperPayOrderResponseToJSONTyped(json, false);
}

export function ResponseWrapperPayOrderResponseToJSONTyped(value?: ResponseWrapperPayOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PayOrderResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

