/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { ViewReportJobStatusResponse } from './ViewReportJobStatusResponse';
import {
    ViewReportJobStatusResponseFromJSON,
    ViewReportJobStatusResponseFromJSONTyped,
    ViewReportJobStatusResponseToJSON,
    ViewReportJobStatusResponseToJSONTyped,
} from './ViewReportJobStatusResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperViewReportJobStatusResponse
 */
export interface ResponseWrapperViewReportJobStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperViewReportJobStatusResponse
     */
    success: boolean;
    /**
     * 
     * @type {ViewReportJobStatusResponse}
     * @memberof ResponseWrapperViewReportJobStatusResponse
     */
    data: ViewReportJobStatusResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperViewReportJobStatusResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperViewReportJobStatusResponse interface.
 */
export function instanceOfResponseWrapperViewReportJobStatusResponse(value: object): value is ResponseWrapperViewReportJobStatusResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperViewReportJobStatusResponseFromJSON(json: any): ResponseWrapperViewReportJobStatusResponse {
    return ResponseWrapperViewReportJobStatusResponseFromJSONTyped(json, false);
}

export function ResponseWrapperViewReportJobStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperViewReportJobStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ViewReportJobStatusResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperViewReportJobStatusResponseToJSON(json: any): ResponseWrapperViewReportJobStatusResponse {
    return ResponseWrapperViewReportJobStatusResponseToJSONTyped(json, false);
}

export function ResponseWrapperViewReportJobStatusResponseToJSONTyped(value?: ResponseWrapperViewReportJobStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ViewReportJobStatusResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

