/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { PlaceOrderResponse } from './PlaceOrderResponse';
import {
    PlaceOrderResponseFromJSON,
    PlaceOrderResponseFromJSONTyped,
    PlaceOrderResponseToJSON,
    PlaceOrderResponseToJSONTyped,
} from './PlaceOrderResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperPlaceOrderResponse
 */
export interface ResponseWrapperPlaceOrderResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperPlaceOrderResponse
     */
    success: boolean;
    /**
     * 
     * @type {PlaceOrderResponse}
     * @memberof ResponseWrapperPlaceOrderResponse
     */
    data: PlaceOrderResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperPlaceOrderResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperPlaceOrderResponse interface.
 */
export function instanceOfResponseWrapperPlaceOrderResponse(value: object): value is ResponseWrapperPlaceOrderResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperPlaceOrderResponseFromJSON(json: any): ResponseWrapperPlaceOrderResponse {
    return ResponseWrapperPlaceOrderResponseFromJSONTyped(json, false);
}

export function ResponseWrapperPlaceOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperPlaceOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PlaceOrderResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperPlaceOrderResponseToJSON(json: any): ResponseWrapperPlaceOrderResponse {
    return ResponseWrapperPlaceOrderResponseToJSONTyped(json, false);
}

export function ResponseWrapperPlaceOrderResponseToJSONTyped(value?: ResponseWrapperPlaceOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PlaceOrderResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

