/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateReviewResponse } from './CreateReviewResponse';
import {
    CreateReviewResponseFromJSON,
    CreateReviewResponseFromJSONTyped,
    CreateReviewResponseToJSON,
    CreateReviewResponseToJSONTyped,
} from './CreateReviewResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperCreateReviewResponse
 */
export interface ResponseWrapperCreateReviewResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperCreateReviewResponse
     */
    success: boolean;
    /**
     * 
     * @type {CreateReviewResponse}
     * @memberof ResponseWrapperCreateReviewResponse
     */
    data: CreateReviewResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperCreateReviewResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperCreateReviewResponse interface.
 */
export function instanceOfResponseWrapperCreateReviewResponse(value: object): value is ResponseWrapperCreateReviewResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperCreateReviewResponseFromJSON(json: any): ResponseWrapperCreateReviewResponse {
    return ResponseWrapperCreateReviewResponseFromJSONTyped(json, false);
}

export function ResponseWrapperCreateReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperCreateReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CreateReviewResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperCreateReviewResponseToJSON(json: any): ResponseWrapperCreateReviewResponse {
    return ResponseWrapperCreateReviewResponseToJSONTyped(json, false);
}

export function ResponseWrapperCreateReviewResponseToJSONTyped(value?: ResponseWrapperCreateReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CreateReviewResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

