/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HideOrRestoreReviewResponse } from './HideOrRestoreReviewResponse';
import {
    HideOrRestoreReviewResponseFromJSON,
    HideOrRestoreReviewResponseFromJSONTyped,
    HideOrRestoreReviewResponseToJSON,
    HideOrRestoreReviewResponseToJSONTyped,
} from './HideOrRestoreReviewResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperHideOrRestoreReviewResponse
 */
export interface ResponseWrapperHideOrRestoreReviewResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperHideOrRestoreReviewResponse
     */
    success: boolean;
    /**
     * 
     * @type {HideOrRestoreReviewResponse}
     * @memberof ResponseWrapperHideOrRestoreReviewResponse
     */
    data: HideOrRestoreReviewResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperHideOrRestoreReviewResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperHideOrRestoreReviewResponse interface.
 */
export function instanceOfResponseWrapperHideOrRestoreReviewResponse(value: object): value is ResponseWrapperHideOrRestoreReviewResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperHideOrRestoreReviewResponseFromJSON(json: any): ResponseWrapperHideOrRestoreReviewResponse {
    return ResponseWrapperHideOrRestoreReviewResponseFromJSONTyped(json, false);
}

export function ResponseWrapperHideOrRestoreReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperHideOrRestoreReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': HideOrRestoreReviewResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperHideOrRestoreReviewResponseToJSON(json: any): ResponseWrapperHideOrRestoreReviewResponse {
    return ResponseWrapperHideOrRestoreReviewResponseToJSONTyped(json, false);
}

export function ResponseWrapperHideOrRestoreReviewResponseToJSONTyped(value?: ResponseWrapperHideOrRestoreReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': HideOrRestoreReviewResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

