/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerifyPasswordResetResponse } from './VerifyPasswordResetResponse';
import {
    VerifyPasswordResetResponseFromJSON,
    VerifyPasswordResetResponseFromJSONTyped,
    VerifyPasswordResetResponseToJSON,
    VerifyPasswordResetResponseToJSONTyped,
} from './VerifyPasswordResetResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperVerifyPasswordResetResponse
 */
export interface ResponseWrapperVerifyPasswordResetResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperVerifyPasswordResetResponse
     */
    success: boolean;
    /**
     * 
     * @type {VerifyPasswordResetResponse}
     * @memberof ResponseWrapperVerifyPasswordResetResponse
     */
    data: VerifyPasswordResetResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperVerifyPasswordResetResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperVerifyPasswordResetResponse interface.
 */
export function instanceOfResponseWrapperVerifyPasswordResetResponse(value: object): value is ResponseWrapperVerifyPasswordResetResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperVerifyPasswordResetResponseFromJSON(json: any): ResponseWrapperVerifyPasswordResetResponse {
    return ResponseWrapperVerifyPasswordResetResponseFromJSONTyped(json, false);
}

export function ResponseWrapperVerifyPasswordResetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperVerifyPasswordResetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': VerifyPasswordResetResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperVerifyPasswordResetResponseToJSON(json: any): ResponseWrapperVerifyPasswordResetResponse {
    return ResponseWrapperVerifyPasswordResetResponseToJSONTyped(json, false);
}

export function ResponseWrapperVerifyPasswordResetResponseToJSONTyped(value?: ResponseWrapperVerifyPasswordResetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': VerifyPasswordResetResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

