/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperData2
 */
export interface ResponseWrapperData2 {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperData2
     */
    success: boolean;
    /**
     * 
     * @type {any}
     * @memberof ResponseWrapperData2
     */
    data: any | null;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperData2
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperData2 interface.
 */
export function instanceOfResponseWrapperData2(value: object): value is ResponseWrapperData2 {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperData2FromJSON(json: any): ResponseWrapperData2 {
    return ResponseWrapperData2FromJSONTyped(json, false);
}

export function ResponseWrapperData2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperData2 {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': json['data'],
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperData2ToJSON(json: any): ResponseWrapperData2 {
    return ResponseWrapperData2ToJSONTyped(json, false);
}

export function ResponseWrapperData2ToJSONTyped(value?: ResponseWrapperData2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': value['data'],
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

