/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { DeactivateBookResponse } from './DeactivateBookResponse';
import {
    DeactivateBookResponseFromJSON,
    DeactivateBookResponseFromJSONTyped,
    DeactivateBookResponseToJSON,
    DeactivateBookResponseToJSONTyped,
} from './DeactivateBookResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperDeactivateBookResponse
 */
export interface ResponseWrapperDeactivateBookResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperDeactivateBookResponse
     */
    success: boolean;
    /**
     * 
     * @type {DeactivateBookResponse}
     * @memberof ResponseWrapperDeactivateBookResponse
     */
    data: DeactivateBookResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperDeactivateBookResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperDeactivateBookResponse interface.
 */
export function instanceOfResponseWrapperDeactivateBookResponse(value: object): value is ResponseWrapperDeactivateBookResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperDeactivateBookResponseFromJSON(json: any): ResponseWrapperDeactivateBookResponse {
    return ResponseWrapperDeactivateBookResponseFromJSONTyped(json, false);
}

export function ResponseWrapperDeactivateBookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperDeactivateBookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': DeactivateBookResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperDeactivateBookResponseToJSON(json: any): ResponseWrapperDeactivateBookResponse {
    return ResponseWrapperDeactivateBookResponseToJSONTyped(json, false);
}

export function ResponseWrapperDeactivateBookResponseToJSONTyped(value?: ResponseWrapperDeactivateBookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': DeactivateBookResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

