/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateCartItemQuantityResponse } from './UpdateCartItemQuantityResponse';
import {
    UpdateCartItemQuantityResponseFromJSON,
    UpdateCartItemQuantityResponseFromJSONTyped,
    UpdateCartItemQuantityResponseToJSON,
    UpdateCartItemQuantityResponseToJSONTyped,
} from './UpdateCartItemQuantityResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperUpdateCartItemQuantityResponse
 */
export interface ResponseWrapperUpdateCartItemQuantityResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperUpdateCartItemQuantityResponse
     */
    success: boolean;
    /**
     * 
     * @type {UpdateCartItemQuantityResponse}
     * @memberof ResponseWrapperUpdateCartItemQuantityResponse
     */
    data: UpdateCartItemQuantityResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperUpdateCartItemQuantityResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperUpdateCartItemQuantityResponse interface.
 */
export function instanceOfResponseWrapperUpdateCartItemQuantityResponse(value: object): value is ResponseWrapperUpdateCartItemQuantityResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperUpdateCartItemQuantityResponseFromJSON(json: any): ResponseWrapperUpdateCartItemQuantityResponse {
    return ResponseWrapperUpdateCartItemQuantityResponseFromJSONTyped(json, false);
}

export function ResponseWrapperUpdateCartItemQuantityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperUpdateCartItemQuantityResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': UpdateCartItemQuantityResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperUpdateCartItemQuantityResponseToJSON(json: any): ResponseWrapperUpdateCartItemQuantityResponse {
    return ResponseWrapperUpdateCartItemQuantityResponseToJSONTyped(json, false);
}

export function ResponseWrapperUpdateCartItemQuantityResponseToJSONTyped(value?: ResponseWrapperUpdateCartItemQuantityResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': UpdateCartItemQuantityResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

