/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponseOrderSummaryResponse } from './PaginatedResponseOrderSummaryResponse';
import {
    PaginatedResponseOrderSummaryResponseFromJSON,
    PaginatedResponseOrderSummaryResponseFromJSONTyped,
    PaginatedResponseOrderSummaryResponseToJSON,
    PaginatedResponseOrderSummaryResponseToJSONTyped,
} from './PaginatedResponseOrderSummaryResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperPaginatedResponseOrderSummaryResponse
 */
export interface ResponseWrapperPaginatedResponseOrderSummaryResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperPaginatedResponseOrderSummaryResponse
     */
    success: boolean;
    /**
     * 
     * @type {PaginatedResponseOrderSummaryResponse}
     * @memberof ResponseWrapperPaginatedResponseOrderSummaryResponse
     */
    data: PaginatedResponseOrderSummaryResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperPaginatedResponseOrderSummaryResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperPaginatedResponseOrderSummaryResponse interface.
 */
export function instanceOfResponseWrapperPaginatedResponseOrderSummaryResponse(value: object): value is ResponseWrapperPaginatedResponseOrderSummaryResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperPaginatedResponseOrderSummaryResponseFromJSON(json: any): ResponseWrapperPaginatedResponseOrderSummaryResponse {
    return ResponseWrapperPaginatedResponseOrderSummaryResponseFromJSONTyped(json, false);
}

export function ResponseWrapperPaginatedResponseOrderSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperPaginatedResponseOrderSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PaginatedResponseOrderSummaryResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperPaginatedResponseOrderSummaryResponseToJSON(json: any): ResponseWrapperPaginatedResponseOrderSummaryResponse {
    return ResponseWrapperPaginatedResponseOrderSummaryResponseToJSONTyped(json, false);
}

export function ResponseWrapperPaginatedResponseOrderSummaryResponseToJSONTyped(value?: ResponseWrapperPaginatedResponseOrderSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PaginatedResponseOrderSummaryResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

