/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { PaginatedResponseReviewWithBookItemResponse } from './PaginatedResponseReviewWithBookItemResponse';
import {
    PaginatedResponseReviewWithBookItemResponseFromJSON,
    PaginatedResponseReviewWithBookItemResponseFromJSONTyped,
    PaginatedResponseReviewWithBookItemResponseToJSON,
    PaginatedResponseReviewWithBookItemResponseToJSONTyped,
} from './PaginatedResponseReviewWithBookItemResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperPaginatedResponseReviewWithBookItemResponse
 */
export interface ResponseWrapperPaginatedResponseReviewWithBookItemResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperPaginatedResponseReviewWithBookItemResponse
     */
    success: boolean;
    /**
     * 
     * @type {PaginatedResponseReviewWithBookItemResponse}
     * @memberof ResponseWrapperPaginatedResponseReviewWithBookItemResponse
     */
    data: PaginatedResponseReviewWithBookItemResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperPaginatedResponseReviewWithBookItemResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperPaginatedResponseReviewWithBookItemResponse interface.
 */
export function instanceOfResponseWrapperPaginatedResponseReviewWithBookItemResponse(value: object): value is ResponseWrapperPaginatedResponseReviewWithBookItemResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperPaginatedResponseReviewWithBookItemResponseFromJSON(json: any): ResponseWrapperPaginatedResponseReviewWithBookItemResponse {
    return ResponseWrapperPaginatedResponseReviewWithBookItemResponseFromJSONTyped(json, false);
}

export function ResponseWrapperPaginatedResponseReviewWithBookItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperPaginatedResponseReviewWithBookItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PaginatedResponseReviewWithBookItemResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperPaginatedResponseReviewWithBookItemResponseToJSON(json: any): ResponseWrapperPaginatedResponseReviewWithBookItemResponse {
    return ResponseWrapperPaginatedResponseReviewWithBookItemResponseToJSONTyped(json, false);
}

export function ResponseWrapperPaginatedResponseReviewWithBookItemResponseToJSONTyped(value?: ResponseWrapperPaginatedResponseReviewWithBookItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PaginatedResponseReviewWithBookItemResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

