/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OAuthLoginUrlResponse } from './OAuthLoginUrlResponse';
import {
    OAuthLoginUrlResponseFromJSON,
    OAuthLoginUrlResponseFromJSONTyped,
    OAuthLoginUrlResponseToJSON,
    OAuthLoginUrlResponseToJSONTyped,
} from './OAuthLoginUrlResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperOAuthLoginUrlResponse
 */
export interface ResponseWrapperOAuthLoginUrlResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperOAuthLoginUrlResponse
     */
    success: boolean;
    /**
     * 
     * @type {OAuthLoginUrlResponse}
     * @memberof ResponseWrapperOAuthLoginUrlResponse
     */
    data: OAuthLoginUrlResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperOAuthLoginUrlResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperOAuthLoginUrlResponse interface.
 */
export function instanceOfResponseWrapperOAuthLoginUrlResponse(value: object): value is ResponseWrapperOAuthLoginUrlResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperOAuthLoginUrlResponseFromJSON(json: any): ResponseWrapperOAuthLoginUrlResponse {
    return ResponseWrapperOAuthLoginUrlResponseFromJSONTyped(json, false);
}

export function ResponseWrapperOAuthLoginUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperOAuthLoginUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': OAuthLoginUrlResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperOAuthLoginUrlResponseToJSON(json: any): ResponseWrapperOAuthLoginUrlResponse {
    return ResponseWrapperOAuthLoginUrlResponseToJSONTyped(json, false);
}

export function ResponseWrapperOAuthLoginUrlResponseToJSONTyped(value?: ResponseWrapperOAuthLoginUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': OAuthLoginUrlResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

