/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewBookDetailResponse } from './ViewBookDetailResponse';
import {
    ViewBookDetailResponseFromJSON,
    ViewBookDetailResponseFromJSONTyped,
    ViewBookDetailResponseToJSON,
    ViewBookDetailResponseToJSONTyped,
} from './ViewBookDetailResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperViewBookDetailResponse
 */
export interface ResponseWrapperViewBookDetailResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperViewBookDetailResponse
     */
    success: boolean;
    /**
     * 
     * @type {ViewBookDetailResponse}
     * @memberof ResponseWrapperViewBookDetailResponse
     */
    data: ViewBookDetailResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperViewBookDetailResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperViewBookDetailResponse interface.
 */
export function instanceOfResponseWrapperViewBookDetailResponse(value: object): value is ResponseWrapperViewBookDetailResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperViewBookDetailResponseFromJSON(json: any): ResponseWrapperViewBookDetailResponse {
    return ResponseWrapperViewBookDetailResponseFromJSONTyped(json, false);
}

export function ResponseWrapperViewBookDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperViewBookDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ViewBookDetailResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperViewBookDetailResponseToJSON(json: any): ResponseWrapperViewBookDetailResponse {
    return ResponseWrapperViewBookDetailResponseToJSONTyped(json, false);
}

export function ResponseWrapperViewBookDetailResponseToJSONTyped(value?: ResponseWrapperViewBookDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ViewBookDetailResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

