/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { PaginatedResponseUserListItemResponse } from './PaginatedResponseUserListItemResponse';
import {
    PaginatedResponseUserListItemResponseFromJSON,
    PaginatedResponseUserListItemResponseFromJSONTyped,
    PaginatedResponseUserListItemResponseToJSON,
    PaginatedResponseUserListItemResponseToJSONTyped,
} from './PaginatedResponseUserListItemResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperPaginatedResponseUserListItemResponse
 */
export interface ResponseWrapperPaginatedResponseUserListItemResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperPaginatedResponseUserListItemResponse
     */
    success: boolean;
    /**
     * 
     * @type {PaginatedResponseUserListItemResponse}
     * @memberof ResponseWrapperPaginatedResponseUserListItemResponse
     */
    data: PaginatedResponseUserListItemResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperPaginatedResponseUserListItemResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperPaginatedResponseUserListItemResponse interface.
 */
export function instanceOfResponseWrapperPaginatedResponseUserListItemResponse(value: object): value is ResponseWrapperPaginatedResponseUserListItemResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperPaginatedResponseUserListItemResponseFromJSON(json: any): ResponseWrapperPaginatedResponseUserListItemResponse {
    return ResponseWrapperPaginatedResponseUserListItemResponseFromJSONTyped(json, false);
}

export function ResponseWrapperPaginatedResponseUserListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperPaginatedResponseUserListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PaginatedResponseUserListItemResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperPaginatedResponseUserListItemResponseToJSON(json: any): ResponseWrapperPaginatedResponseUserListItemResponse {
    return ResponseWrapperPaginatedResponseUserListItemResponseToJSONTyped(json, false);
}

export function ResponseWrapperPaginatedResponseUserListItemResponseToJSONTyped(value?: ResponseWrapperPaginatedResponseUserListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PaginatedResponseUserListItemResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

