/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { InventoryMetricsResponse } from './InventoryMetricsResponse';
import {
    InventoryMetricsResponseFromJSON,
    InventoryMetricsResponseFromJSONTyped,
    InventoryMetricsResponseToJSON,
    InventoryMetricsResponseToJSONTyped,
} from './InventoryMetricsResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperInventoryMetricsResponse
 */
export interface ResponseWrapperInventoryMetricsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperInventoryMetricsResponse
     */
    success: boolean;
    /**
     * 
     * @type {InventoryMetricsResponse}
     * @memberof ResponseWrapperInventoryMetricsResponse
     */
    data: InventoryMetricsResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperInventoryMetricsResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperInventoryMetricsResponse interface.
 */
export function instanceOfResponseWrapperInventoryMetricsResponse(value: object): value is ResponseWrapperInventoryMetricsResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperInventoryMetricsResponseFromJSON(json: any): ResponseWrapperInventoryMetricsResponse {
    return ResponseWrapperInventoryMetricsResponseFromJSONTyped(json, false);
}

export function ResponseWrapperInventoryMetricsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperInventoryMetricsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': InventoryMetricsResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperInventoryMetricsResponseToJSON(json: any): ResponseWrapperInventoryMetricsResponse {
    return ResponseWrapperInventoryMetricsResponseToJSONTyped(json, false);
}

export function ResponseWrapperInventoryMetricsResponseToJSONTyped(value?: ResponseWrapperInventoryMetricsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': InventoryMetricsResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

