/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewOrderDetailResponse } from './ViewOrderDetailResponse';
import {
    ViewOrderDetailResponseFromJSON,
    ViewOrderDetailResponseFromJSONTyped,
    ViewOrderDetailResponseToJSON,
    ViewOrderDetailResponseToJSONTyped,
} from './ViewOrderDetailResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperViewOrderDetailResponse
 */
export interface ResponseWrapperViewOrderDetailResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperViewOrderDetailResponse
     */
    success: boolean;
    /**
     * 
     * @type {ViewOrderDetailResponse}
     * @memberof ResponseWrapperViewOrderDetailResponse
     */
    data: ViewOrderDetailResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperViewOrderDetailResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperViewOrderDetailResponse interface.
 */
export function instanceOfResponseWrapperViewOrderDetailResponse(value: object): value is ResponseWrapperViewOrderDetailResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperViewOrderDetailResponseFromJSON(json: any): ResponseWrapperViewOrderDetailResponse {
    return ResponseWrapperViewOrderDetailResponseFromJSONTyped(json, false);
}

export function ResponseWrapperViewOrderDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperViewOrderDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ViewOrderDetailResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperViewOrderDetailResponseToJSON(json: any): ResponseWrapperViewOrderDetailResponse {
    return ResponseWrapperViewOrderDetailResponseToJSONTyped(json, false);
}

export function ResponseWrapperViewOrderDetailResponseToJSONTyped(value?: ResponseWrapperViewOrderDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ViewOrderDetailResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

