/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivateBookResponse } from './ActivateBookResponse';
import {
    ActivateBookResponseFromJSON,
    ActivateBookResponseFromJSONTyped,
    ActivateBookResponseToJSON,
    ActivateBookResponseToJSONTyped,
} from './ActivateBookResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperActivateBookResponse
 */
export interface ResponseWrapperActivateBookResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperActivateBookResponse
     */
    success: boolean;
    /**
     * 
     * @type {ActivateBookResponse}
     * @memberof ResponseWrapperActivateBookResponse
     */
    data: ActivateBookResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperActivateBookResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperActivateBookResponse interface.
 */
export function instanceOfResponseWrapperActivateBookResponse(value: object): value is ResponseWrapperActivateBookResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperActivateBookResponseFromJSON(json: any): ResponseWrapperActivateBookResponse {
    return ResponseWrapperActivateBookResponseFromJSONTyped(json, false);
}

export function ResponseWrapperActivateBookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperActivateBookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ActivateBookResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperActivateBookResponseToJSON(json: any): ResponseWrapperActivateBookResponse {
    return ResponseWrapperActivateBookResponseToJSONTyped(json, false);
}

export function ResponseWrapperActivateBookResponseToJSONTyped(value?: ResponseWrapperActivateBookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ActivateBookResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

