/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateCollectionResponse } from './CreateCollectionResponse';
import {
    CreateCollectionResponseFromJSON,
    CreateCollectionResponseFromJSONTyped,
    CreateCollectionResponseToJSON,
    CreateCollectionResponseToJSONTyped,
} from './CreateCollectionResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperCreateCollectionResponse
 */
export interface ResponseWrapperCreateCollectionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperCreateCollectionResponse
     */
    success: boolean;
    /**
     * 
     * @type {CreateCollectionResponse}
     * @memberof ResponseWrapperCreateCollectionResponse
     */
    data: CreateCollectionResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperCreateCollectionResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperCreateCollectionResponse interface.
 */
export function instanceOfResponseWrapperCreateCollectionResponse(value: object): value is ResponseWrapperCreateCollectionResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperCreateCollectionResponseFromJSON(json: any): ResponseWrapperCreateCollectionResponse {
    return ResponseWrapperCreateCollectionResponseFromJSONTyped(json, false);
}

export function ResponseWrapperCreateCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperCreateCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CreateCollectionResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperCreateCollectionResponseToJSON(json: any): ResponseWrapperCreateCollectionResponse {
    return ResponseWrapperCreateCollectionResponseToJSONTyped(json, false);
}

export function ResponseWrapperCreateCollectionResponseToJSONTyped(value?: ResponseWrapperCreateCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CreateCollectionResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

