/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { UploadBookCoverResponse } from './UploadBookCoverResponse';
import {
    UploadBookCoverResponseFromJSON,
    UploadBookCoverResponseFromJSONTyped,
    UploadBookCoverResponseToJSON,
    UploadBookCoverResponseToJSONTyped,
} from './UploadBookCoverResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperUploadBookCoverResponse
 */
export interface ResponseWrapperUploadBookCoverResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperUploadBookCoverResponse
     */
    success: boolean;
    /**
     * 
     * @type {UploadBookCoverResponse}
     * @memberof ResponseWrapperUploadBookCoverResponse
     */
    data: UploadBookCoverResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperUploadBookCoverResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperUploadBookCoverResponse interface.
 */
export function instanceOfResponseWrapperUploadBookCoverResponse(value: object): value is ResponseWrapperUploadBookCoverResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperUploadBookCoverResponseFromJSON(json: any): ResponseWrapperUploadBookCoverResponse {
    return ResponseWrapperUploadBookCoverResponseFromJSONTyped(json, false);
}

export function ResponseWrapperUploadBookCoverResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperUploadBookCoverResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': UploadBookCoverResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperUploadBookCoverResponseToJSON(json: any): ResponseWrapperUploadBookCoverResponse {
    return ResponseWrapperUploadBookCoverResponseToJSONTyped(json, false);
}

export function ResponseWrapperUploadBookCoverResponseToJSONTyped(value?: ResponseWrapperUploadBookCoverResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': UploadBookCoverResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

