/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { CreateReportJobResponse } from './CreateReportJobResponse';
import {
    CreateReportJobResponseFromJSON,
    CreateReportJobResponseFromJSONTyped,
    CreateReportJobResponseToJSON,
    CreateReportJobResponseToJSONTyped,
} from './CreateReportJobResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperCreateReportJobResponse
 */
export interface ResponseWrapperCreateReportJobResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperCreateReportJobResponse
     */
    success: boolean;
    /**
     * 
     * @type {CreateReportJobResponse}
     * @memberof ResponseWrapperCreateReportJobResponse
     */
    data: CreateReportJobResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperCreateReportJobResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperCreateReportJobResponse interface.
 */
export function instanceOfResponseWrapperCreateReportJobResponse(value: object): value is ResponseWrapperCreateReportJobResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperCreateReportJobResponseFromJSON(json: any): ResponseWrapperCreateReportJobResponse {
    return ResponseWrapperCreateReportJobResponseFromJSONTyped(json, false);
}

export function ResponseWrapperCreateReportJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperCreateReportJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CreateReportJobResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperCreateReportJobResponseToJSON(json: any): ResponseWrapperCreateReportJobResponse {
    return ResponseWrapperCreateReportJobResponseToJSONTyped(json, false);
}

export function ResponseWrapperCreateReportJobResponseToJSONTyped(value?: ResponseWrapperCreateReportJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CreateReportJobResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

