/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UpdateOrderStatusResponse } from './UpdateOrderStatusResponse';
import {
    UpdateOrderStatusResponseFromJSON,
    UpdateOrderStatusResponseFromJSONTyped,
    UpdateOrderStatusResponseToJSON,
    UpdateOrderStatusResponseToJSONTyped,
} from './UpdateOrderStatusResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperUpdateOrderStatusResponse
 */
export interface ResponseWrapperUpdateOrderStatusResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperUpdateOrderStatusResponse
     */
    success: boolean;
    /**
     * 
     * @type {UpdateOrderStatusResponse}
     * @memberof ResponseWrapperUpdateOrderStatusResponse
     */
    data: UpdateOrderStatusResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperUpdateOrderStatusResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperUpdateOrderStatusResponse interface.
 */
export function instanceOfResponseWrapperUpdateOrderStatusResponse(value: object): value is ResponseWrapperUpdateOrderStatusResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperUpdateOrderStatusResponseFromJSON(json: any): ResponseWrapperUpdateOrderStatusResponse {
    return ResponseWrapperUpdateOrderStatusResponseFromJSONTyped(json, false);
}

export function ResponseWrapperUpdateOrderStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperUpdateOrderStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': UpdateOrderStatusResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperUpdateOrderStatusResponseToJSON(json: any): ResponseWrapperUpdateOrderStatusResponse {
    return ResponseWrapperUpdateOrderStatusResponseToJSONTyped(json, false);
}

export function ResponseWrapperUpdateOrderStatusResponseToJSONTyped(value?: ResponseWrapperUpdateOrderStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': UpdateOrderStatusResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

