/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { ChangePasswordResponse } from './ChangePasswordResponse';
import {
    ChangePasswordResponseFromJSON,
    ChangePasswordResponseFromJSONTyped,
    ChangePasswordResponseToJSON,
    ChangePasswordResponseToJSONTyped,
} from './ChangePasswordResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperChangePasswordResponse
 */
export interface ResponseWrapperChangePasswordResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperChangePasswordResponse
     */
    success: boolean;
    /**
     * 
     * @type {ChangePasswordResponse}
     * @memberof ResponseWrapperChangePasswordResponse
     */
    data: ChangePasswordResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperChangePasswordResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperChangePasswordResponse interface.
 */
export function instanceOfResponseWrapperChangePasswordResponse(value: object): value is ResponseWrapperChangePasswordResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperChangePasswordResponseFromJSON(json: any): ResponseWrapperChangePasswordResponse {
    return ResponseWrapperChangePasswordResponseFromJSONTyped(json, false);
}

export function ResponseWrapperChangePasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperChangePasswordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ChangePasswordResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperChangePasswordResponseToJSON(json: any): ResponseWrapperChangePasswordResponse {
    return ResponseWrapperChangePasswordResponseToJSONTyped(json, false);
}

export function ResponseWrapperChangePasswordResponseToJSONTyped(value?: ResponseWrapperChangePasswordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ChangePasswordResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

