/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { SoftDeleteCategoryResponse } from './SoftDeleteCategoryResponse';
import {
    SoftDeleteCategoryResponseFromJSON,
    SoftDeleteCategoryResponseFromJSONTyped,
    SoftDeleteCategoryResponseToJSON,
    SoftDeleteCategoryResponseToJSONTyped,
} from './SoftDeleteCategoryResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperSoftDeleteCategoryResponse
 */
export interface ResponseWrapperSoftDeleteCategoryResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperSoftDeleteCategoryResponse
     */
    success: boolean;
    /**
     * 
     * @type {SoftDeleteCategoryResponse}
     * @memberof ResponseWrapperSoftDeleteCategoryResponse
     */
    data: SoftDeleteCategoryResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperSoftDeleteCategoryResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperSoftDeleteCategoryResponse interface.
 */
export function instanceOfResponseWrapperSoftDeleteCategoryResponse(value: object): value is ResponseWrapperSoftDeleteCategoryResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperSoftDeleteCategoryResponseFromJSON(json: any): ResponseWrapperSoftDeleteCategoryResponse {
    return ResponseWrapperSoftDeleteCategoryResponseFromJSONTyped(json, false);
}

export function ResponseWrapperSoftDeleteCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperSoftDeleteCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SoftDeleteCategoryResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperSoftDeleteCategoryResponseToJSON(json: any): ResponseWrapperSoftDeleteCategoryResponse {
    return ResponseWrapperSoftDeleteCategoryResponseToJSONTyped(json, false);
}

export function ResponseWrapperSoftDeleteCategoryResponseToJSONTyped(value?: ResponseWrapperSoftDeleteCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SoftDeleteCategoryResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

