/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { SoftDeleteBookResponse } from './SoftDeleteBookResponse';
import {
    SoftDeleteBookResponseFromJSON,
    SoftDeleteBookResponseFromJSONTyped,
    SoftDeleteBookResponseToJSON,
    SoftDeleteBookResponseToJSONTyped,
} from './SoftDeleteBookResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperSoftDeleteBookResponse
 */
export interface ResponseWrapperSoftDeleteBookResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperSoftDeleteBookResponse
     */
    success: boolean;
    /**
     * 
     * @type {SoftDeleteBookResponse}
     * @memberof ResponseWrapperSoftDeleteBookResponse
     */
    data: SoftDeleteBookResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperSoftDeleteBookResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperSoftDeleteBookResponse interface.
 */
export function instanceOfResponseWrapperSoftDeleteBookResponse(value: object): value is ResponseWrapperSoftDeleteBookResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperSoftDeleteBookResponseFromJSON(json: any): ResponseWrapperSoftDeleteBookResponse {
    return ResponseWrapperSoftDeleteBookResponseFromJSONTyped(json, false);
}

export function ResponseWrapperSoftDeleteBookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperSoftDeleteBookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SoftDeleteBookResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperSoftDeleteBookResponseToJSON(json: any): ResponseWrapperSoftDeleteBookResponse {
    return ResponseWrapperSoftDeleteBookResponseToJSONTyped(json, false);
}

export function ResponseWrapperSoftDeleteBookResponseToJSONTyped(value?: ResponseWrapperSoftDeleteBookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SoftDeleteBookResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

