/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResetPasswordResponse } from './ResetPasswordResponse';
import {
    ResetPasswordResponseFromJSON,
    ResetPasswordResponseFromJSONTyped,
    ResetPasswordResponseToJSON,
    ResetPasswordResponseToJSONTyped,
} from './ResetPasswordResponse';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';

/**
 * 
 * @export
 * @interface ResponseWrapperResetPasswordResponse
 */
export interface ResponseWrapperResetPasswordResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperResetPasswordResponse
     */
    success: boolean;
    /**
     * 
     * @type {ResetPasswordResponse}
     * @memberof ResponseWrapperResetPasswordResponse
     */
    data: ResetPasswordResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperResetPasswordResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperResetPasswordResponse interface.
 */
export function instanceOfResponseWrapperResetPasswordResponse(value: object): value is ResponseWrapperResetPasswordResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperResetPasswordResponseFromJSON(json: any): ResponseWrapperResetPasswordResponse {
    return ResponseWrapperResetPasswordResponseFromJSONTyped(json, false);
}

export function ResponseWrapperResetPasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperResetPasswordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ResetPasswordResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperResetPasswordResponseToJSON(json: any): ResponseWrapperResetPasswordResponse {
    return ResponseWrapperResetPasswordResponseToJSONTyped(json, false);
}

export function ResponseWrapperResetPasswordResponseToJSONTyped(value?: ResponseWrapperResetPasswordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ResetPasswordResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

