/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { CollectionListItemResponse } from './CollectionListItemResponse';
import {
    CollectionListItemResponseFromJSON,
    CollectionListItemResponseFromJSONTyped,
    CollectionListItemResponseToJSON,
    CollectionListItemResponseToJSONTyped,
} from './CollectionListItemResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperData
 */
export interface ResponseWrapperData {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperData
     */
    success: boolean;
    /**
     * 
     * @type {Array<CollectionListItemResponse>}
     * @memberof ResponseWrapperData
     */
    data: Array<CollectionListItemResponse>;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperData
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperData interface.
 */
export function instanceOfResponseWrapperData(value: object): value is ResponseWrapperData {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperDataFromJSON(json: any): ResponseWrapperData {
    return ResponseWrapperDataFromJSONTyped(json, false);
}

export function ResponseWrapperDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperData {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(CollectionListItemResponseFromJSON)),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperDataToJSON(json: any): ResponseWrapperData {
    return ResponseWrapperDataToJSONTyped(json, false);
}

export function ResponseWrapperDataToJSONTyped(value?: ResponseWrapperData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(CollectionListItemResponseToJSON)),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

