/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResponseMeta } from './ResponseMeta';
import {
    ResponseMetaFromJSON,
    ResponseMetaFromJSONTyped,
    ResponseMetaToJSON,
    ResponseMetaToJSONTyped,
} from './ResponseMeta';
import type { GetMyWishlistResponse } from './GetMyWishlistResponse';
import {
    GetMyWishlistResponseFromJSON,
    GetMyWishlistResponseFromJSONTyped,
    GetMyWishlistResponseToJSON,
    GetMyWishlistResponseToJSONTyped,
} from './GetMyWishlistResponse';

/**
 * 
 * @export
 * @interface ResponseWrapperGetMyWishlistResponse
 */
export interface ResponseWrapperGetMyWishlistResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ResponseWrapperGetMyWishlistResponse
     */
    success: boolean;
    /**
     * 
     * @type {GetMyWishlistResponse}
     * @memberof ResponseWrapperGetMyWishlistResponse
     */
    data: GetMyWishlistResponse;
    /**
     * 
     * @type {ResponseMeta}
     * @memberof ResponseWrapperGetMyWishlistResponse
     */
    meta: ResponseMeta;
}

/**
 * Check if a given object implements the ResponseWrapperGetMyWishlistResponse interface.
 */
export function instanceOfResponseWrapperGetMyWishlistResponse(value: object): value is ResponseWrapperGetMyWishlistResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ResponseWrapperGetMyWishlistResponseFromJSON(json: any): ResponseWrapperGetMyWishlistResponse {
    return ResponseWrapperGetMyWishlistResponseFromJSONTyped(json, false);
}

export function ResponseWrapperGetMyWishlistResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseWrapperGetMyWishlistResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': GetMyWishlistResponseFromJSON(json['data']),
        'meta': ResponseMetaFromJSON(json['meta']),
    };
}

export function ResponseWrapperGetMyWishlistResponseToJSON(json: any): ResponseWrapperGetMyWishlistResponse {
    return ResponseWrapperGetMyWishlistResponseToJSONTyped(json, false);
}

export function ResponseWrapperGetMyWishlistResponseToJSONTyped(value?: ResponseWrapperGetMyWishlistResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': GetMyWishlistResponseToJSON(value['data']),
        'meta': ResponseMetaToJSON(value['meta']),
    };
}

