/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SoftDeleteCollectionResponse
 */
export interface SoftDeleteCollectionResponse {
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteCollectionResponse
     */
    message: string;
}

/**
 * Check if a given object implements the SoftDeleteCollectionResponse interface.
 */
export function instanceOfSoftDeleteCollectionResponse(value: object): value is SoftDeleteCollectionResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SoftDeleteCollectionResponseFromJSON(json: any): SoftDeleteCollectionResponse {
    return SoftDeleteCollectionResponseFromJSONTyped(json, false);
}

export function SoftDeleteCollectionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoftDeleteCollectionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function SoftDeleteCollectionResponseToJSON(json: any): SoftDeleteCollectionResponse {
    return SoftDeleteCollectionResponseToJSONTyped(json, false);
}

export function SoftDeleteCollectionResponseToJSONTyped(value?: SoftDeleteCollectionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

