/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookCategoryResponse } from './BookCategoryResponse';
import {
    BookCategoryResponseFromJSON,
    BookCategoryResponseFromJSONTyped,
    BookCategoryResponseToJSON,
    BookCategoryResponseToJSONTyped,
} from './BookCategoryResponse';
import type { BookPublisherResponse } from './BookPublisherResponse';
import {
    BookPublisherResponseFromJSON,
    BookPublisherResponseFromJSONTyped,
    BookPublisherResponseToJSON,
    BookPublisherResponseToJSONTyped,
} from './BookPublisherResponse';
import type { BookAuthorItemResponse } from './BookAuthorItemResponse';
import {
    BookAuthorItemResponseFromJSON,
    BookAuthorItemResponseFromJSONTyped,
    BookAuthorItemResponseToJSON,
    BookAuthorItemResponseToJSONTyped,
} from './BookAuthorItemResponse';

/**
 * 
 * @export
 * @interface SoftDeleteBookResponse
 */
export interface SoftDeleteBookResponse {
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteBookResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteBookResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteBookResponse
     */
    price: string;
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteBookResponse
     */
    language: string;
    /**
     * 
     * @type {number}
     * @memberof SoftDeleteBookResponse
     */
    stockQuantity: number;
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteBookResponse
     */
    coverUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteBookResponse
     */
    isbn: string | null;
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteBookResponse
     */
    description: string | null;
    /**
     * 
     * @type {number}
     * @memberof SoftDeleteBookResponse
     */
    pageCount: number | null;
    /**
     * 
     * @type {Date}
     * @memberof SoftDeleteBookResponse
     */
    publishedDate: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof SoftDeleteBookResponse
     */
    isActive: boolean;
    /**
     * 
     * @type {BookPublisherResponse}
     * @memberof SoftDeleteBookResponse
     */
    publisher: BookPublisherResponse | null;
    /**
     * 
     * @type {BookCategoryResponse}
     * @memberof SoftDeleteBookResponse
     */
    category: BookCategoryResponse | null;
    /**
     * 
     * @type {Array<BookAuthorItemResponse>}
     * @memberof SoftDeleteBookResponse
     */
    authors: Array<BookAuthorItemResponse>;
    /**
     * 
     * @type {Date}
     * @memberof SoftDeleteBookResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SoftDeleteBookResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the SoftDeleteBookResponse interface.
 */
export function instanceOfSoftDeleteBookResponse(value: object): value is SoftDeleteBookResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('stockQuantity' in value) || value['stockQuantity'] === undefined) return false;
    if (!('coverUrl' in value) || value['coverUrl'] === undefined) return false;
    if (!('isbn' in value) || value['isbn'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('pageCount' in value) || value['pageCount'] === undefined) return false;
    if (!('publishedDate' in value) || value['publishedDate'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('publisher' in value) || value['publisher'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('authors' in value) || value['authors'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SoftDeleteBookResponseFromJSON(json: any): SoftDeleteBookResponse {
    return SoftDeleteBookResponseFromJSONTyped(json, false);
}

export function SoftDeleteBookResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoftDeleteBookResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'price': json['price'],
        'language': json['language'],
        'stockQuantity': json['stock_quantity'],
        'coverUrl': json['cover_url'],
        'isbn': json['isbn'],
        'description': json['description'],
        'pageCount': json['page_count'],
        'publishedDate': (json['published_date'] == null ? null : new Date(json['published_date'])),
        'isActive': json['is_active'],
        'publisher': BookPublisherResponseFromJSON(json['publisher']),
        'category': BookCategoryResponseFromJSON(json['category']),
        'authors': ((json['authors'] as Array<any>).map(BookAuthorItemResponseFromJSON)),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SoftDeleteBookResponseToJSON(json: any): SoftDeleteBookResponse {
    return SoftDeleteBookResponseToJSONTyped(json, false);
}

export function SoftDeleteBookResponseToJSONTyped(value?: SoftDeleteBookResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'price': value['price'],
        'language': value['language'],
        'stock_quantity': value['stockQuantity'],
        'cover_url': value['coverUrl'],
        'isbn': value['isbn'],
        'description': value['description'],
        'page_count': value['pageCount'],
        'published_date': (value['publishedDate'] == null ? null : (value['publishedDate'] as any).toISOString().substring(0,10)),
        'is_active': value['isActive'],
        'publisher': BookPublisherResponseToJSON(value['publisher']),
        'category': BookCategoryResponseToJSON(value['category']),
        'authors': ((value['authors'] as Array<any>).map(BookAuthorItemResponseToJSON)),
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

