/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SoftDeleteMeResponse
 */
export interface SoftDeleteMeResponse {
    /**
     * 
     * @type {string}
     * @memberof SoftDeleteMeResponse
     */
    message: string;
}

/**
 * Check if a given object implements the SoftDeleteMeResponse interface.
 */
export function instanceOfSoftDeleteMeResponse(value: object): value is SoftDeleteMeResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function SoftDeleteMeResponseFromJSON(json: any): SoftDeleteMeResponse {
    return SoftDeleteMeResponseFromJSONTyped(json, false);
}

export function SoftDeleteMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SoftDeleteMeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function SoftDeleteMeResponseToJSON(json: any): SoftDeleteMeResponse {
    return SoftDeleteMeResponseToJSONTyped(json, false);
}

export function SoftDeleteMeResponseToJSONTyped(value?: SoftDeleteMeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

