/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnreadNotificationCountResponse
 */
export interface UnreadNotificationCountResponse {
    /**
     * 
     * @type {number}
     * @memberof UnreadNotificationCountResponse
     */
    unreadCount: number;
}

/**
 * Check if a given object implements the UnreadNotificationCountResponse interface.
 */
export function instanceOfUnreadNotificationCountResponse(value: object): value is UnreadNotificationCountResponse {
    if (!('unreadCount' in value) || value['unreadCount'] === undefined) return false;
    return true;
}

export function UnreadNotificationCountResponseFromJSON(json: any): UnreadNotificationCountResponse {
    return UnreadNotificationCountResponseFromJSONTyped(json, false);
}

export function UnreadNotificationCountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnreadNotificationCountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'unreadCount': json['unread_count'],
    };
}

export function UnreadNotificationCountResponseToJSON(json: any): UnreadNotificationCountResponse {
    return UnreadNotificationCountResponseToJSONTyped(json, false);
}

export function UnreadNotificationCountResponseToJSONTyped(value?: UnreadNotificationCountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unread_count': value['unreadCount'],
    };
}

