/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAuthorRequest
 */
export interface UpdateAuthorRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateAuthorRequest
     */
    name: string;
}

/**
 * Check if a given object implements the UpdateAuthorRequest interface.
 */
export function instanceOfUpdateAuthorRequest(value: object): value is UpdateAuthorRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateAuthorRequestFromJSON(json: any): UpdateAuthorRequest {
    return UpdateAuthorRequestFromJSONTyped(json, false);
}

export function UpdateAuthorRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAuthorRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function UpdateAuthorRequestToJSON(json: any): UpdateAuthorRequest {
    return UpdateAuthorRequestToJSONTyped(json, false);
}

export function UpdateAuthorRequestToJSONTyped(value?: UpdateAuthorRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

