/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMyReviewRequest
 */
export interface UpdateMyReviewRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateMyReviewRequest
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyReviewRequest
     */
    comment?: string | null;
}

/**
 * Check if a given object implements the UpdateMyReviewRequest interface.
 */
export function instanceOfUpdateMyReviewRequest(value: object): value is UpdateMyReviewRequest {
    return true;
}

export function UpdateMyReviewRequestFromJSON(json: any): UpdateMyReviewRequest {
    return UpdateMyReviewRequestFromJSONTyped(json, false);
}

export function UpdateMyReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'] == null ? undefined : json['rating'],
        'comment': json['comment'] == null ? undefined : json['comment'],
    };
}

export function UpdateMyReviewRequestToJSON(json: any): UpdateMyReviewRequest {
    return UpdateMyReviewRequestToJSONTyped(json, false);
}

export function UpdateMyReviewRequestToJSONTyped(value?: UpdateMyReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating': value['rating'],
        'comment': value['comment'],
    };
}

