/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePublisherRequest
 */
export interface UpdatePublisherRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePublisherRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePublisherRequest
     */
    website?: string | null;
}

/**
 * Check if a given object implements the UpdatePublisherRequest interface.
 */
export function instanceOfUpdatePublisherRequest(value: object): value is UpdatePublisherRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdatePublisherRequestFromJSON(json: any): UpdatePublisherRequest {
    return UpdatePublisherRequestFromJSONTyped(json, false);
}

export function UpdatePublisherRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePublisherRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'website': json['website'] == null ? undefined : json['website'],
    };
}

export function UpdatePublisherRequestToJSON(json: any): UpdatePublisherRequest {
    return UpdatePublisherRequestToJSONTyped(json, false);
}

export function UpdatePublisherRequestToJSONTyped(value?: UpdatePublisherRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'website': value['website'],
    };
}

