/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateMyReviewResponse
 */
export interface UpdateMyReviewResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateMyReviewResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyReviewResponse
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyReviewResponse
     */
    userId: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyReviewResponse
     */
    orderItemId: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateMyReviewResponse
     */
    rating: number | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateMyReviewResponse
     */
    comment: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdateMyReviewResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateMyReviewResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the UpdateMyReviewResponse interface.
 */
export function instanceOfUpdateMyReviewResponse(value: object): value is UpdateMyReviewResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('orderItemId' in value) || value['orderItemId'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('comment' in value) || value['comment'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UpdateMyReviewResponseFromJSON(json: any): UpdateMyReviewResponse {
    return UpdateMyReviewResponseFromJSONTyped(json, false);
}

export function UpdateMyReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMyReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'bookId': json['book_id'],
        'userId': json['user_id'],
        'orderItemId': json['order_item_id'],
        'rating': json['rating'],
        'comment': json['comment'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UpdateMyReviewResponseToJSON(json: any): UpdateMyReviewResponse {
    return UpdateMyReviewResponseToJSONTyped(json, false);
}

export function UpdateMyReviewResponseToJSONTyped(value?: UpdateMyReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'book_id': value['bookId'],
        'user_id': value['userId'],
        'order_item_id': value['orderItemId'],
        'rating': value['rating'],
        'comment': value['comment'],
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

