/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateBookStockQuantityRequest
 */
export interface UpdateBookStockQuantityRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateBookStockQuantityRequest
     */
    stockQuantity: number;
}

/**
 * Check if a given object implements the UpdateBookStockQuantityRequest interface.
 */
export function instanceOfUpdateBookStockQuantityRequest(value: object): value is UpdateBookStockQuantityRequest {
    if (!('stockQuantity' in value) || value['stockQuantity'] === undefined) return false;
    return true;
}

export function UpdateBookStockQuantityRequestFromJSON(json: any): UpdateBookStockQuantityRequest {
    return UpdateBookStockQuantityRequestFromJSONTyped(json, false);
}

export function UpdateBookStockQuantityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBookStockQuantityRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'stockQuantity': json['stock_quantity'],
    };
}

export function UpdateBookStockQuantityRequestToJSON(json: any): UpdateBookStockQuantityRequest {
    return UpdateBookStockQuantityRequestToJSONTyped(json, false);
}

export function UpdateBookStockQuantityRequestToJSONTyped(value?: UpdateBookStockQuantityRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stock_quantity': value['stockQuantity'],
    };
}

