/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCollectionRequest
 */
export interface UpdateCollectionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCollectionRequest
     */
    urlSlug: string;
}

/**
 * Check if a given object implements the UpdateCollectionRequest interface.
 */
export function instanceOfUpdateCollectionRequest(value: object): value is UpdateCollectionRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('urlSlug' in value) || value['urlSlug'] === undefined) return false;
    return true;
}

export function UpdateCollectionRequestFromJSON(json: any): UpdateCollectionRequest {
    return UpdateCollectionRequestFromJSONTyped(json, false);
}

export function UpdateCollectionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCollectionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'urlSlug': json['url_slug'],
    };
}

export function UpdateCollectionRequestToJSON(json: any): UpdateCollectionRequest {
    return UpdateCollectionRequestToJSONTyped(json, false);
}

export function UpdateCollectionRequestToJSONTyped(value?: UpdateCollectionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'url_slug': value['urlSlug'],
    };
}

