/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRole } from './UserRole';
import {
    UserRoleFromJSON,
    UserRoleFromJSONTyped,
    UserRoleToJSON,
    UserRoleToJSONTyped,
} from './UserRole';
import type { UserStatus } from './UserStatus';
import {
    UserStatusFromJSON,
    UserStatusFromJSONTyped,
    UserStatusToJSON,
    UserStatusToJSONTyped,
} from './UserStatus';

/**
 * 
 * @export
 * @interface UserProfileResponse
 */
export interface UserProfileResponse {
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    fullName: string;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileResponse
     */
    dateOfBirth: Date | null;
    /**
     * 
     * @type {UserRole}
     * @memberof UserProfileResponse
     */
    role: UserRole;
    /**
     * 
     * @type {UserStatus}
     * @memberof UserProfileResponse
     */
    status: UserStatus;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    avatarUrl: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfileResponse
     */
    havePassword: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileResponse
     */
    lastLoginAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileResponse
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the UserProfileResponse interface.
 */
export function instanceOfUserProfileResponse(value: object): value is UserProfileResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('dateOfBirth' in value) || value['dateOfBirth'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('avatarUrl' in value) || value['avatarUrl'] === undefined) return false;
    if (!('havePassword' in value) || value['havePassword'] === undefined) return false;
    if (!('lastLoginAt' in value) || value['lastLoginAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function UserProfileResponseFromJSON(json: any): UserProfileResponse {
    return UserProfileResponseFromJSONTyped(json, false);
}

export function UserProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'fullName': json['full_name'],
        'dateOfBirth': (json['date_of_birth'] == null ? null : new Date(json['date_of_birth'])),
        'role': UserRoleFromJSON(json['role']),
        'status': UserStatusFromJSON(json['status']),
        'avatarUrl': json['avatar_url'],
        'havePassword': json['have_password'],
        'lastLoginAt': (json['last_login_at'] == null ? null : new Date(json['last_login_at'])),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function UserProfileResponseToJSON(json: any): UserProfileResponse {
    return UserProfileResponseToJSONTyped(json, false);
}

export function UserProfileResponseToJSONTyped(value?: UserProfileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'full_name': value['fullName'],
        'date_of_birth': (value['dateOfBirth'] == null ? null : (value['dateOfBirth'] as any).toISOString().substring(0,10)),
        'role': UserRoleToJSON(value['role']),
        'status': UserStatusToJSON(value['status']),
        'avatar_url': value['avatarUrl'],
        'have_password': value['havePassword'],
        'last_login_at': (value['lastLoginAt'] == null ? null : (value['lastLoginAt'] as any).toISOString()),
        'created_at': ((value['createdAt']).toISOString()),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

