/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidationErrorDetail
 */
export interface ValidationErrorDetail {
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorDetail
     */
    field: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorDetail
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof ValidationErrorDetail
     */
    code: string;
}

/**
 * Check if a given object implements the ValidationErrorDetail interface.
 */
export function instanceOfValidationErrorDetail(value: object): value is ValidationErrorDetail {
    if (!('field' in value) || value['field'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ValidationErrorDetailFromJSON(json: any): ValidationErrorDetail {
    return ValidationErrorDetailFromJSONTyped(json, false);
}

export function ValidationErrorDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidationErrorDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'field': json['field'],
        'message': json['message'],
        'code': json['code'],
    };
}

export function ValidationErrorDetailToJSON(json: any): ValidationErrorDetail {
    return ValidationErrorDetailToJSONTyped(json, false);
}

export function ValidationErrorDetailToJSONTyped(value?: ValidationErrorDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field': value['field'],
        'message': value['message'],
        'code': value['code'],
    };
}

