/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyEmailResponse
 */
export interface VerifyEmailResponse {
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof VerifyEmailResponse
     */
    message: string;
}

/**
 * Check if a given object implements the VerifyEmailResponse interface.
 */
export function instanceOfVerifyEmailResponse(value: object): value is VerifyEmailResponse {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function VerifyEmailResponseFromJSON(json: any): VerifyEmailResponse {
    return VerifyEmailResponseFromJSONTyped(json, false);
}

export function VerifyEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'message': json['message'],
    };
}

export function VerifyEmailResponseToJSON(json: any): VerifyEmailResponse {
    return VerifyEmailResponseToJSONTyped(json, false);
}

export function VerifyEmailResponseToJSONTyped(value?: VerifyEmailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'message': value['message'],
    };
}

