/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewPublisherDetailResponse
 */
export interface ViewPublisherDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof ViewPublisherDetailResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ViewPublisherDetailResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ViewPublisherDetailResponse
     */
    website: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ViewPublisherDetailResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ViewPublisherDetailResponse interface.
 */
export function instanceOfViewPublisherDetailResponse(value: object): value is ViewPublisherDetailResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ViewPublisherDetailResponseFromJSON(json: any): ViewPublisherDetailResponse {
    return ViewPublisherDetailResponseFromJSONTyped(json, false);
}

export function ViewPublisherDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewPublisherDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'website': json['website'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ViewPublisherDetailResponseToJSON(json: any): ViewPublisherDetailResponse {
    return ViewPublisherDetailResponseToJSONTyped(json, false);
}

export function ViewPublisherDetailResponseToJSONTyped(value?: ViewPublisherDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'website': value['website'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

