/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReportJobStatus } from './ReportJobStatus';
import {
    ReportJobStatusFromJSON,
    ReportJobStatusFromJSONTyped,
    ReportJobStatusToJSON,
    ReportJobStatusToJSONTyped,
} from './ReportJobStatus';

/**
 * 
 * @export
 * @interface ViewReportJobStatusResponse
 */
export interface ViewReportJobStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof ViewReportJobStatusResponse
     */
    jobId: string;
    /**
     * 
     * @type {ReportJobStatus}
     * @memberof ViewReportJobStatusResponse
     */
    status: ReportJobStatus;
    /**
     * 
     * @type {Date}
     * @memberof ViewReportJobStatusResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ViewReportJobStatusResponse
     */
    completedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ViewReportJobStatusResponse
     */
    downloadUrl: string | null;
}



/**
 * Check if a given object implements the ViewReportJobStatusResponse interface.
 */
export function instanceOfViewReportJobStatusResponse(value: object): value is ViewReportJobStatusResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('downloadUrl' in value) || value['downloadUrl'] === undefined) return false;
    return true;
}

export function ViewReportJobStatusResponseFromJSON(json: any): ViewReportJobStatusResponse {
    return ViewReportJobStatusResponseFromJSONTyped(json, false);
}

export function ViewReportJobStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewReportJobStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'status': ReportJobStatusFromJSON(json['status']),
        'createdAt': (new Date(json['created_at'])),
        'completedAt': (json['completed_at'] == null ? null : new Date(json['completed_at'])),
        'downloadUrl': json['download_url'],
    };
}

export function ViewReportJobStatusResponseToJSON(json: any): ViewReportJobStatusResponse {
    return ViewReportJobStatusResponseToJSONTyped(json, false);
}

export function ViewReportJobStatusResponseToJSONTyped(value?: ViewReportJobStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'status': ReportJobStatusToJSON(value['status']),
        'created_at': ((value['createdAt']).toISOString()),
        'completed_at': (value['completedAt'] == null ? null : (value['completedAt'] as any).toISOString()),
        'download_url': value['downloadUrl'],
    };
}

