/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentSummaryResponse } from './PaymentSummaryResponse';
import {
    PaymentSummaryResponseFromJSON,
    PaymentSummaryResponseFromJSONTyped,
    PaymentSummaryResponseToJSON,
    PaymentSummaryResponseToJSONTyped,
} from './PaymentSummaryResponse';
import type { BaseOrderItemResponse } from './BaseOrderItemResponse';
import {
    BaseOrderItemResponseFromJSON,
    BaseOrderItemResponseFromJSONTyped,
    BaseOrderItemResponseToJSON,
    BaseOrderItemResponseToJSONTyped,
} from './BaseOrderItemResponse';
import type { OrderStatus } from './OrderStatus';
import {
    OrderStatusFromJSON,
    OrderStatusFromJSONTyped,
    OrderStatusToJSON,
    OrderStatusToJSONTyped,
} from './OrderStatus';

/**
 * 
 * @export
 * @interface ViewOrderDetailResponse
 */
export interface ViewOrderDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof ViewOrderDetailResponse
     */
    id: string;
    /**
     * 
     * @type {OrderStatus}
     * @memberof ViewOrderDetailResponse
     */
    status: OrderStatus;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderDetailResponse
     */
    subtotal: string;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderDetailResponse
     */
    shippingCost: string;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderDetailResponse
     */
    total: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ViewOrderDetailResponse
     */
    addressSnapshot: { [key: string]: any; };
    /**
     * 
     * @type {Array<BaseOrderItemResponse>}
     * @memberof ViewOrderDetailResponse
     */
    items: Array<BaseOrderItemResponse>;
    /**
     * 
     * @type {Date}
     * @memberof ViewOrderDetailResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ViewOrderDetailResponse
     */
    userId: string;
    /**
     * 
     * @type {PaymentSummaryResponse}
     * @memberof ViewOrderDetailResponse
     */
    payment: PaymentSummaryResponse | null;
    /**
     * 
     * @type {Date}
     * @memberof ViewOrderDetailResponse
     */
    updatedAt: Date;
}



/**
 * Check if a given object implements the ViewOrderDetailResponse interface.
 */
export function instanceOfViewOrderDetailResponse(value: object): value is ViewOrderDetailResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('subtotal' in value) || value['subtotal'] === undefined) return false;
    if (!('shippingCost' in value) || value['shippingCost'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('addressSnapshot' in value) || value['addressSnapshot'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('payment' in value) || value['payment'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ViewOrderDetailResponseFromJSON(json: any): ViewOrderDetailResponse {
    return ViewOrderDetailResponseFromJSONTyped(json, false);
}

export function ViewOrderDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewOrderDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': OrderStatusFromJSON(json['status']),
        'subtotal': json['subtotal'],
        'shippingCost': json['shipping_cost'],
        'total': json['total'],
        'addressSnapshot': json['address_snapshot'],
        'items': ((json['items'] as Array<any>).map(BaseOrderItemResponseFromJSON)),
        'createdAt': (new Date(json['created_at'])),
        'userId': json['user_id'],
        'payment': PaymentSummaryResponseFromJSON(json['payment']),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ViewOrderDetailResponseToJSON(json: any): ViewOrderDetailResponse {
    return ViewOrderDetailResponseToJSONTyped(json, false);
}

export function ViewOrderDetailResponseToJSONTyped(value?: ViewOrderDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': OrderStatusToJSON(value['status']),
        'subtotal': value['subtotal'],
        'shipping_cost': value['shippingCost'],
        'total': value['total'],
        'address_snapshot': value['addressSnapshot'],
        'items': ((value['items'] as Array<any>).map(BaseOrderItemResponseToJSON)),
        'created_at': ((value['createdAt']).toISOString()),
        'user_id': value['userId'],
        'payment': PaymentSummaryResponseToJSON(value['payment']),
        'updated_at': ((value['updatedAt']).toISOString()),
    };
}

