/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryResponse } from './CategoryResponse';
import {
    CategoryResponseFromJSON,
    CategoryResponseFromJSONTyped,
    CategoryResponseToJSON,
    CategoryResponseToJSONTyped,
} from './CategoryResponse';

/**
 * 
 * @export
 * @interface ViewCollectionDetailResponse
 */
export interface ViewCollectionDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof ViewCollectionDetailResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ViewCollectionDetailResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ViewCollectionDetailResponse
     */
    urlSlug: string;
    /**
     * 
     * @type {Array<CategoryResponse>}
     * @memberof ViewCollectionDetailResponse
     */
    categories: Array<CategoryResponse>;
    /**
     * 
     * @type {Date}
     * @memberof ViewCollectionDetailResponse
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the ViewCollectionDetailResponse interface.
 */
export function instanceOfViewCollectionDetailResponse(value: object): value is ViewCollectionDetailResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('urlSlug' in value) || value['urlSlug'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ViewCollectionDetailResponseFromJSON(json: any): ViewCollectionDetailResponse {
    return ViewCollectionDetailResponseFromJSONTyped(json, false);
}

export function ViewCollectionDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewCollectionDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'urlSlug': json['url_slug'],
        'categories': ((json['categories'] as Array<any>).map(CategoryResponseFromJSON)),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ViewCollectionDetailResponseToJSON(json: any): ViewCollectionDetailResponse {
    return ViewCollectionDetailResponseToJSONTyped(json, false);
}

export function ViewCollectionDetailResponseToJSONTyped(value?: ViewCollectionDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'url_slug': value['urlSlug'],
        'categories': ((value['categories'] as Array<any>).map(CategoryResponseToJSON)),
        'created_at': ((value['createdAt']).toISOString()),
    };
}

