/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  GoogleLoginRequest,
  LoginRequest,
  RegisterRequest,
  ResendVerificationRequest,
  ResponseWrapperRegisterResponse,
  ResponseWrapperResendVerificationResponse,
  ResponseWrapperTokenResponse,
  ResponseWrapperVerifyEmailResponse,
  VerifyEmailRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GoogleLoginRequestFromJSON,
    GoogleLoginRequestToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    ResendVerificationRequestFromJSON,
    ResendVerificationRequestToJSON,
    ResponseWrapperRegisterResponseFromJSON,
    ResponseWrapperRegisterResponseToJSON,
    ResponseWrapperResendVerificationResponseFromJSON,
    ResponseWrapperResendVerificationResponseToJSON,
    ResponseWrapperTokenResponseFromJSON,
    ResponseWrapperTokenResponseToJSON,
    ResponseWrapperVerifyEmailResponseFromJSON,
    ResponseWrapperVerifyEmailResponseToJSON,
    VerifyEmailRequestFromJSON,
    VerifyEmailRequestToJSON,
} from '../models/index';

export interface CredentialLoginRequest {
    loginRequest: LoginRequest;
}

export interface LoginWithGoogleRequest {
    googleLoginRequest: GoogleLoginRequest;
}

export interface RegisterOperationRequest {
    registerRequest: RegisterRequest;
}

export interface ResendEmailVerificationRequest {
    resendVerificationRequest: ResendVerificationRequest;
}

export interface VerifyEmailOperationRequest {
    verifyEmailRequest: VerifyEmailRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Credential Login
     */
    async credentialLoginRaw(requestParameters: CredentialLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperTokenResponse>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling credentialLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/app/v1/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperTokenResponseFromJSON(jsonValue));
    }

    /**
     * Credential Login
     */
    async credentialLogin(requestParameters: CredentialLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperTokenResponse> {
        const response = await this.credentialLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Google Login
     */
    async loginWithGoogleRaw(requestParameters: LoginWithGoogleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperTokenResponse>> {
        if (requestParameters['googleLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'googleLoginRequest',
                'Required parameter "googleLoginRequest" was null or undefined when calling loginWithGoogle().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/app/v1/auth/login/google`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GoogleLoginRequestToJSON(requestParameters['googleLoginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperTokenResponseFromJSON(jsonValue));
    }

    /**
     * Google Login
     */
    async loginWithGoogle(requestParameters: LoginWithGoogleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperTokenResponse> {
        const response = await this.loginWithGoogleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Register
     */
    async registerRaw(requestParameters: RegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperRegisterResponse>> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/app/v1/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperRegisterResponseFromJSON(jsonValue));
    }

    /**
     * Register
     */
    async register(requestParameters: RegisterOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperRegisterResponse> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resend Verification
     */
    async resendEmailVerificationRaw(requestParameters: ResendEmailVerificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperResendVerificationResponse>> {
        if (requestParameters['resendVerificationRequest'] == null) {
            throw new runtime.RequiredError(
                'resendVerificationRequest',
                'Required parameter "resendVerificationRequest" was null or undefined when calling resendEmailVerification().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/app/v1/auth/resend-verification`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResendVerificationRequestToJSON(requestParameters['resendVerificationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperResendVerificationResponseFromJSON(jsonValue));
    }

    /**
     * Resend Verification
     */
    async resendEmailVerification(requestParameters: ResendEmailVerificationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperResendVerificationResponse> {
        const response = await this.resendEmailVerificationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify Email
     */
    async verifyEmailRaw(requestParameters: VerifyEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperVerifyEmailResponse>> {
        if (requestParameters['verifyEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyEmailRequest',
                'Required parameter "verifyEmailRequest" was null or undefined when calling verifyEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/app/v1/auth/verify-email`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyEmailRequestToJSON(requestParameters['verifyEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperVerifyEmailResponseFromJSON(jsonValue));
    }

    /**
     * Verify Email
     */
    async verifyEmail(requestParameters: VerifyEmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperVerifyEmailResponse> {
        const response = await this.verifyEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
