/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateAuthorRequest,
  ErrorResponse,
  ResponseWrapperCreateAuthorResponse,
  ResponseWrapperPaginatedResponseAuthorListItemResponse,
  ResponseWrapperSoftDeleteAuthorResponse,
  ResponseWrapperUpdateAuthorResponse,
  ResponseWrapperViewAuthorDetailResponse,
  UpdateAuthorRequest,
} from '../models/index';
import {
    CreateAuthorRequestFromJSON,
    CreateAuthorRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseWrapperCreateAuthorResponseFromJSON,
    ResponseWrapperCreateAuthorResponseToJSON,
    ResponseWrapperPaginatedResponseAuthorListItemResponseFromJSON,
    ResponseWrapperPaginatedResponseAuthorListItemResponseToJSON,
    ResponseWrapperSoftDeleteAuthorResponseFromJSON,
    ResponseWrapperSoftDeleteAuthorResponseToJSON,
    ResponseWrapperUpdateAuthorResponseFromJSON,
    ResponseWrapperUpdateAuthorResponseToJSON,
    ResponseWrapperViewAuthorDetailResponseFromJSON,
    ResponseWrapperViewAuthorDetailResponseToJSON,
    UpdateAuthorRequestFromJSON,
    UpdateAuthorRequestToJSON,
} from '../models/index';

export interface CreateAuthorOperationRequest {
    createAuthorRequest: CreateAuthorRequest;
}

export interface FindAuthorsRequest {
    sort?: string | null;
    page?: number;
    pageSize?: number;
    search?: string | null;
}

export interface SoftDeleteAuthorRequest {
    authorId: string;
}

export interface UpdateAuthorOperationRequest {
    authorId: string;
    updateAuthorRequest: UpdateAuthorRequest;
}

export interface ViewAuthorDetailRequest {
    authorId: string;
}

/**
 * 
 */
export class AuthorApi extends runtime.BaseAPI {

    /**
     * Create Author
     */
    async createAuthorRaw(requestParameters: CreateAuthorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperCreateAuthorResponse>> {
        if (requestParameters['createAuthorRequest'] == null) {
            throw new runtime.RequiredError(
                'createAuthorRequest',
                'Required parameter "createAuthorRequest" was null or undefined when calling createAuthor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/authors`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAuthorRequestToJSON(requestParameters['createAuthorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperCreateAuthorResponseFromJSON(jsonValue));
    }

    /**
     * Create Author
     */
    async createAuthor(requestParameters: CreateAuthorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperCreateAuthorResponse> {
        const response = await this.createAuthorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Authors
     */
    async findAuthorsRaw(requestParameters: FindAuthorsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPaginatedResponseAuthorListItemResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/app/v1/authors`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPaginatedResponseAuthorListItemResponseFromJSON(jsonValue));
    }

    /**
     * Find Authors
     */
    async findAuthors(requestParameters: FindAuthorsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPaginatedResponseAuthorListItemResponse> {
        const response = await this.findAuthorsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft Delete Author
     */
    async softDeleteAuthorRaw(requestParameters: SoftDeleteAuthorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperSoftDeleteAuthorResponse>> {
        if (requestParameters['authorId'] == null) {
            throw new runtime.RequiredError(
                'authorId',
                'Required parameter "authorId" was null or undefined when calling softDeleteAuthor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/authors/{author_id}`.replace(`{${"author_id"}}`, encodeURIComponent(String(requestParameters['authorId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperSoftDeleteAuthorResponseFromJSON(jsonValue));
    }

    /**
     * Soft Delete Author
     */
    async softDeleteAuthor(requestParameters: SoftDeleteAuthorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperSoftDeleteAuthorResponse> {
        const response = await this.softDeleteAuthorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Author
     */
    async updateAuthorRaw(requestParameters: UpdateAuthorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUpdateAuthorResponse>> {
        if (requestParameters['authorId'] == null) {
            throw new runtime.RequiredError(
                'authorId',
                'Required parameter "authorId" was null or undefined when calling updateAuthor().'
            );
        }

        if (requestParameters['updateAuthorRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAuthorRequest',
                'Required parameter "updateAuthorRequest" was null or undefined when calling updateAuthor().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/authors/{author_id}`.replace(`{${"author_id"}}`, encodeURIComponent(String(requestParameters['authorId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAuthorRequestToJSON(requestParameters['updateAuthorRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUpdateAuthorResponseFromJSON(jsonValue));
    }

    /**
     * Update Author
     */
    async updateAuthor(requestParameters: UpdateAuthorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUpdateAuthorResponse> {
        const response = await this.updateAuthorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * View Author Detail
     */
    async viewAuthorDetailRaw(requestParameters: ViewAuthorDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperViewAuthorDetailResponse>> {
        if (requestParameters['authorId'] == null) {
            throw new runtime.RequiredError(
                'authorId',
                'Required parameter "authorId" was null or undefined when calling viewAuthorDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/app/v1/authors/{author_id}`.replace(`{${"author_id"}}`, encodeURIComponent(String(requestParameters['authorId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperViewAuthorDetailResponseFromJSON(jsonValue));
    }

    /**
     * View Author Detail
     */
    async viewAuthorDetail(requestParameters: ViewAuthorDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperViewAuthorDetailResponse> {
        const response = await this.viewAuthorDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
