/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCategoryRequest,
  ErrorResponse,
  ResponseWrapperCreateCategoryResponse,
  ResponseWrapperData,
  ResponseWrapperSoftDeleteCategoryResponse,
  ResponseWrapperUpdateCategoryResponse,
  ResponseWrapperViewCategoryDetailResponse,
} from '../models/index';
import {
    CreateCategoryRequestFromJSON,
    CreateCategoryRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseWrapperCreateCategoryResponseFromJSON,
    ResponseWrapperCreateCategoryResponseToJSON,
    ResponseWrapperDataFromJSON,
    ResponseWrapperDataToJSON,
    ResponseWrapperSoftDeleteCategoryResponseFromJSON,
    ResponseWrapperSoftDeleteCategoryResponseToJSON,
    ResponseWrapperUpdateCategoryResponseFromJSON,
    ResponseWrapperUpdateCategoryResponseToJSON,
    ResponseWrapperViewCategoryDetailResponseFromJSON,
    ResponseWrapperViewCategoryDetailResponseToJSON,
} from '../models/index';

export interface CreateCategoryOperationRequest {
    createCategoryRequest: CreateCategoryRequest;
}

export interface FindCategoriesRequest {
    collectionId?: string | null;
}

export interface SoftDeleteCategoryRequest {
    categoryId: string;
}

export interface UpdateCategoryRequest {
    categoryId: string;
    createCategoryRequest: CreateCategoryRequest;
}

export interface ViewCategoryDetailRequest {
    categoryId: string;
}

/**
 * 
 */
export class CategoryApi extends runtime.BaseAPI {

    /**
     * Create Category
     */
    async createCategoryRaw(requestParameters: CreateCategoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperCreateCategoryResponse>> {
        if (requestParameters['createCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'createCategoryRequest',
                'Required parameter "createCategoryRequest" was null or undefined when calling createCategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/categories`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCategoryRequestToJSON(requestParameters['createCategoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperCreateCategoryResponseFromJSON(jsonValue));
    }

    /**
     * Create Category
     */
    async createCategory(requestParameters: CreateCategoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperCreateCategoryResponse> {
        const response = await this.createCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Categories
     */
    async findCategoriesRaw(requestParameters: FindCategoriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperData>> {
        const queryParameters: any = {};

        if (requestParameters['collectionId'] != null) {
            queryParameters['collection_id'] = requestParameters['collectionId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/app/v1/categories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperDataFromJSON(jsonValue));
    }

    /**
     * Find Categories
     */
    async findCategories(requestParameters: FindCategoriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperData> {
        const response = await this.findCategoriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft Delete Category
     */
    async softDeleteCategoryRaw(requestParameters: SoftDeleteCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperSoftDeleteCategoryResponse>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling softDeleteCategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/categories/{category_id}`.replace(`{${"category_id"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperSoftDeleteCategoryResponseFromJSON(jsonValue));
    }

    /**
     * Soft Delete Category
     */
    async softDeleteCategory(requestParameters: SoftDeleteCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperSoftDeleteCategoryResponse> {
        const response = await this.softDeleteCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Category
     */
    async updateCategoryRaw(requestParameters: UpdateCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUpdateCategoryResponse>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling updateCategory().'
            );
        }

        if (requestParameters['createCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'createCategoryRequest',
                'Required parameter "createCategoryRequest" was null or undefined when calling updateCategory().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/categories/{category_id}`.replace(`{${"category_id"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCategoryRequestToJSON(requestParameters['createCategoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUpdateCategoryResponseFromJSON(jsonValue));
    }

    /**
     * Update Category
     */
    async updateCategory(requestParameters: UpdateCategoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUpdateCategoryResponse> {
        const response = await this.updateCategoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * View Category Detail
     */
    async viewCategoryDetailRaw(requestParameters: ViewCategoryDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperViewCategoryDetailResponse>> {
        if (requestParameters['categoryId'] == null) {
            throw new runtime.RequiredError(
                'categoryId',
                'Required parameter "categoryId" was null or undefined when calling viewCategoryDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/app/v1/categories/{category_id}`.replace(`{${"category_id"}}`, encodeURIComponent(String(requestParameters['categoryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperViewCategoryDetailResponseFromJSON(jsonValue));
    }

    /**
     * View Category Detail
     */
    async viewCategoryDetail(requestParameters: ViewCategoryDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperViewCategoryDetailResponse> {
        const response = await this.viewCategoryDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
