/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCollectionRequest,
  ErrorResponse,
  ResponseWrapperCreateCollectionResponse,
  ResponseWrapperData,
  ResponseWrapperSoftDeleteCollectionResponse,
  ResponseWrapperUpdateCollectionResponse,
  ResponseWrapperViewCollectionDetailResponse,
  UpdateCollectionRequest,
} from '../models/index';
import {
    CreateCollectionRequestFromJSON,
    CreateCollectionRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseWrapperCreateCollectionResponseFromJSON,
    ResponseWrapperCreateCollectionResponseToJSON,
    ResponseWrapperDataFromJSON,
    ResponseWrapperDataToJSON,
    ResponseWrapperSoftDeleteCollectionResponseFromJSON,
    ResponseWrapperSoftDeleteCollectionResponseToJSON,
    ResponseWrapperUpdateCollectionResponseFromJSON,
    ResponseWrapperUpdateCollectionResponseToJSON,
    ResponseWrapperViewCollectionDetailResponseFromJSON,
    ResponseWrapperViewCollectionDetailResponseToJSON,
    UpdateCollectionRequestFromJSON,
    UpdateCollectionRequestToJSON,
} from '../models/index';

export interface CreateCollectionOperationRequest {
    createCollectionRequest: CreateCollectionRequest;
}

export interface SoftDeleteCollectionRequest {
    collectionId: string;
}

export interface UpdateCollectionApiAppV1CollectionsCollectionIdPatchRequest {
    collectionId: string;
    updateCollectionRequest: UpdateCollectionRequest;
}

export interface ViewCollectionDetailApiAppV1CollectionsCollectionIdGetRequest {
    collectionId: string;
}

/**
 * 
 */
export class CollectionsApi extends runtime.BaseAPI {

    /**
     * Create Collection
     */
    async createCollectionRaw(requestParameters: CreateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperCreateCollectionResponse>> {
        if (requestParameters['createCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'createCollectionRequest',
                'Required parameter "createCollectionRequest" was null or undefined when calling createCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/collections`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCollectionRequestToJSON(requestParameters['createCollectionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperCreateCollectionResponseFromJSON(jsonValue));
    }

    /**
     * Create Collection
     */
    async createCollection(requestParameters: CreateCollectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperCreateCollectionResponse> {
        const response = await this.createCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Collections
     */
    async findCollectionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperData>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/app/v1/collections`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperDataFromJSON(jsonValue));
    }

    /**
     * Find Collections
     */
    async findCollections(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperData> {
        const response = await this.findCollectionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Soft Delete Collection
     */
    async softDeleteCollectionRaw(requestParameters: SoftDeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperSoftDeleteCollectionResponse>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling softDeleteCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/collections/{collection_id}`.replace(`{${"collection_id"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperSoftDeleteCollectionResponseFromJSON(jsonValue));
    }

    /**
     * Soft Delete Collection
     */
    async softDeleteCollection(requestParameters: SoftDeleteCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperSoftDeleteCollectionResponse> {
        const response = await this.softDeleteCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Collection
     */
    async updateCollectionApiAppV1CollectionsCollectionIdPatchRaw(requestParameters: UpdateCollectionApiAppV1CollectionsCollectionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUpdateCollectionResponse>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling updateCollectionApiAppV1CollectionsCollectionIdPatch().'
            );
        }

        if (requestParameters['updateCollectionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCollectionRequest',
                'Required parameter "updateCollectionRequest" was null or undefined when calling updateCollectionApiAppV1CollectionsCollectionIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/collections/{collection_id}`.replace(`{${"collection_id"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCollectionRequestToJSON(requestParameters['updateCollectionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUpdateCollectionResponseFromJSON(jsonValue));
    }

    /**
     * Update Collection
     */
    async updateCollectionApiAppV1CollectionsCollectionIdPatch(requestParameters: UpdateCollectionApiAppV1CollectionsCollectionIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUpdateCollectionResponse> {
        const response = await this.updateCollectionApiAppV1CollectionsCollectionIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * View Collection Detail
     */
    async viewCollectionDetailApiAppV1CollectionsCollectionIdGetRaw(requestParameters: ViewCollectionDetailApiAppV1CollectionsCollectionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperViewCollectionDetailResponse>> {
        if (requestParameters['collectionId'] == null) {
            throw new runtime.RequiredError(
                'collectionId',
                'Required parameter "collectionId" was null or undefined when calling viewCollectionDetailApiAppV1CollectionsCollectionIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/app/v1/collections/{collection_id}`.replace(`{${"collection_id"}}`, encodeURIComponent(String(requestParameters['collectionId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperViewCollectionDetailResponseFromJSON(jsonValue));
    }

    /**
     * View Collection Detail
     */
    async viewCollectionDetailApiAppV1CollectionsCollectionIdGet(requestParameters: ViewCollectionDetailApiAppV1CollectionsCollectionIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperViewCollectionDetailResponse> {
        const response = await this.viewCollectionDetailApiAppV1CollectionsCollectionIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
