/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ResponseWrapperInventoryMetricsResponse,
  ResponseWrapperPaginatedResponseBaseBookResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseWrapperInventoryMetricsResponseFromJSON,
    ResponseWrapperInventoryMetricsResponseToJSON,
    ResponseWrapperPaginatedResponseBaseBookResponseFromJSON,
    ResponseWrapperPaginatedResponseBaseBookResponseToJSON,
} from '../models/index';

export interface FindLowStockItemsRequest {
    sort?: string | null;
    page?: number;
    pageSize?: number;
    search?: string | null;
    threshold?: number;
}

export interface FindOutOfStockItemsRequest {
    sort?: string | null;
    page?: number;
    pageSize?: number;
    search?: string | null;
}

/**
 * 
 */
export class InventoryApi extends runtime.BaseAPI {

    /**
     * Find Low Stock Items
     */
    async findLowStockItemsRaw(requestParameters: FindLowStockItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPaginatedResponseBaseBookResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['threshold'] != null) {
            queryParameters['threshold'] = requestParameters['threshold'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/inventory/low-stock`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPaginatedResponseBaseBookResponseFromJSON(jsonValue));
    }

    /**
     * Find Low Stock Items
     */
    async findLowStockItems(requestParameters: FindLowStockItemsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPaginatedResponseBaseBookResponse> {
        const response = await this.findLowStockItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Out Of Stock Items
     */
    async findOutOfStockItemsRaw(requestParameters: FindOutOfStockItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPaginatedResponseBaseBookResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/inventory/out-of-stock`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPaginatedResponseBaseBookResponseFromJSON(jsonValue));
    }

    /**
     * Find Out Of Stock Items
     */
    async findOutOfStockItems(requestParameters: FindOutOfStockItemsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPaginatedResponseBaseBookResponse> {
        const response = await this.findOutOfStockItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Inventory Metrics
     */
    async getInventoryMetricsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperInventoryMetricsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/inventory/metrics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperInventoryMetricsResponseFromJSON(jsonValue));
    }

    /**
     * Get Inventory Metrics
     */
    async getInventoryMetrics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperInventoryMetricsResponse> {
        const response = await this.getInventoryMetricsRaw(initOverrides);
        return await response.value();
    }

}
