/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Body,
  ErrorResponse,
  OrderStatus,
  PlaceOrderRequest,
  ResponseWrapperCancelOrderResponse,
  ResponseWrapperPaginatedResponseOrderSummaryResponse,
  ResponseWrapperPayOrderResponse,
  ResponseWrapperPlaceOrderResponse,
  ResponseWrapperUpdateOrderStatusResponse,
  ResponseWrapperViewOrderDetailResponse,
  UpdateOrderStatusRequest,
} from '../models/index';
import {
    BodyFromJSON,
    BodyToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    OrderStatusFromJSON,
    OrderStatusToJSON,
    PlaceOrderRequestFromJSON,
    PlaceOrderRequestToJSON,
    ResponseWrapperCancelOrderResponseFromJSON,
    ResponseWrapperCancelOrderResponseToJSON,
    ResponseWrapperPaginatedResponseOrderSummaryResponseFromJSON,
    ResponseWrapperPaginatedResponseOrderSummaryResponseToJSON,
    ResponseWrapperPayOrderResponseFromJSON,
    ResponseWrapperPayOrderResponseToJSON,
    ResponseWrapperPlaceOrderResponseFromJSON,
    ResponseWrapperPlaceOrderResponseToJSON,
    ResponseWrapperUpdateOrderStatusResponseFromJSON,
    ResponseWrapperUpdateOrderStatusResponseToJSON,
    ResponseWrapperViewOrderDetailResponseFromJSON,
    ResponseWrapperViewOrderDetailResponseToJSON,
    UpdateOrderStatusRequestFromJSON,
    UpdateOrderStatusRequestToJSON,
} from '../models/index';

export interface CancelOrderRequest {
    orderId: string;
}

export interface FindOrdersRequest {
    sort?: string | null;
    page?: number;
    pageSize?: number;
    search?: string | null;
    status?: OrderStatus | null;
    userId?: string | null;
    dateFrom?: Date | null;
    dateTo?: Date | null;
}

export interface PayOrderRequest {
    orderId: string;
    body: Body;
}

export interface PlaceOrderOperationRequest {
    placeOrderRequest: PlaceOrderRequest;
}

export interface UpdateOrderStatusOperationRequest {
    orderId: string;
    updateOrderStatusRequest: UpdateOrderStatusRequest;
}

export interface ViewOrderDetailRequest {
    orderId: string;
}

/**
 * 
 */
export class OrderApi extends runtime.BaseAPI {

    /**
     * Cancel Order
     */
    async cancelOrderRaw(requestParameters: CancelOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperCancelOrderResponse>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling cancelOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/orders/{order_id}/cancel`.replace(`{${"order_id"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperCancelOrderResponseFromJSON(jsonValue));
    }

    /**
     * Cancel Order
     */
    async cancelOrder(requestParameters: CancelOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperCancelOrderResponse> {
        const response = await this.cancelOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Orders
     */
    async findOrdersRaw(requestParameters: FindOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPaginatedResponseOrderSummaryResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['userId'] != null) {
            queryParameters['user_id'] = requestParameters['userId'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = (requestParameters['dateFrom'] as any).toISOString().substring(0,10);
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = (requestParameters['dateTo'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/orders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPaginatedResponseOrderSummaryResponseFromJSON(jsonValue));
    }

    /**
     * Find Orders
     */
    async findOrders(requestParameters: FindOrdersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPaginatedResponseOrderSummaryResponse> {
        const response = await this.findOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Pay Order
     */
    async payOrderRaw(requestParameters: PayOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPayOrderResponse>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling payOrder().'
            );
        }

        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling payOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/orders/{order_id}/payment`.replace(`{${"order_id"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BodyToJSON(requestParameters['body']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPayOrderResponseFromJSON(jsonValue));
    }

    /**
     * Pay Order
     */
    async payOrder(requestParameters: PayOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPayOrderResponse> {
        const response = await this.payOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Place Order
     */
    async placeOrderRaw(requestParameters: PlaceOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPlaceOrderResponse>> {
        if (requestParameters['placeOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'placeOrderRequest',
                'Required parameter "placeOrderRequest" was null or undefined when calling placeOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/orders`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlaceOrderRequestToJSON(requestParameters['placeOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPlaceOrderResponseFromJSON(jsonValue));
    }

    /**
     * Place Order
     */
    async placeOrder(requestParameters: PlaceOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPlaceOrderResponse> {
        const response = await this.placeOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Order Status
     */
    async updateOrderStatusRaw(requestParameters: UpdateOrderStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUpdateOrderStatusResponse>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling updateOrderStatus().'
            );
        }

        if (requestParameters['updateOrderStatusRequest'] == null) {
            throw new runtime.RequiredError(
                'updateOrderStatusRequest',
                'Required parameter "updateOrderStatusRequest" was null or undefined when calling updateOrderStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/orders/{order_id}/status`.replace(`{${"order_id"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrderStatusRequestToJSON(requestParameters['updateOrderStatusRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUpdateOrderStatusResponseFromJSON(jsonValue));
    }

    /**
     * Update Order Status
     */
    async updateOrderStatus(requestParameters: UpdateOrderStatusOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUpdateOrderStatusResponse> {
        const response = await this.updateOrderStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * View Order Detail
     */
    async viewOrderDetailRaw(requestParameters: ViewOrderDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperViewOrderDetailResponse>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling viewOrderDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/orders/{order_id}`.replace(`{${"order_id"}}`, encodeURIComponent(String(requestParameters['orderId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperViewOrderDetailResponseFromJSON(jsonValue));
    }

    /**
     * View Order Detail
     */
    async viewOrderDetail(requestParameters: ViewOrderDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperViewOrderDetailResponse> {
        const response = await this.viewOrderDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
