/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePublisherRequest,
  ErrorResponse,
  ResponseWrapperCreatePublisherResponse,
  ResponseWrapperPaginatedResponseBasePublisherResponse,
  ResponseWrapperSoftDeletePublisherResponse,
  ResponseWrapperUpdatePublisherResponse,
  ResponseWrapperViewPublisherDetailResponse,
  UpdatePublisherRequest,
} from '../models/index';
import {
    CreatePublisherRequestFromJSON,
    CreatePublisherRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ResponseWrapperCreatePublisherResponseFromJSON,
    ResponseWrapperCreatePublisherResponseToJSON,
    ResponseWrapperPaginatedResponseBasePublisherResponseFromJSON,
    ResponseWrapperPaginatedResponseBasePublisherResponseToJSON,
    ResponseWrapperSoftDeletePublisherResponseFromJSON,
    ResponseWrapperSoftDeletePublisherResponseToJSON,
    ResponseWrapperUpdatePublisherResponseFromJSON,
    ResponseWrapperUpdatePublisherResponseToJSON,
    ResponseWrapperViewPublisherDetailResponseFromJSON,
    ResponseWrapperViewPublisherDetailResponseToJSON,
    UpdatePublisherRequestFromJSON,
    UpdatePublisherRequestToJSON,
} from '../models/index';

export interface CreatePublisherOperationRequest {
    createPublisherRequest: CreatePublisherRequest;
}

export interface FindPublishersRequest {
    sort?: string | null;
    page?: number;
    pageSize?: number;
    search?: string | null;
}

export interface SoftDeletePublisherRequest {
    publisherId: string;
}

export interface UpdatePublisherOperationRequest {
    publisherId: string;
    updatePublisherRequest: UpdatePublisherRequest;
}

export interface ViewPublisherDetailRequest {
    publisherId: string;
}

/**
 * 
 */
export class PublisherApi extends runtime.BaseAPI {

    /**
     * Create Publisher
     */
    async createPublisherRaw(requestParameters: CreatePublisherOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperCreatePublisherResponse>> {
        if (requestParameters['createPublisherRequest'] == null) {
            throw new runtime.RequiredError(
                'createPublisherRequest',
                'Required parameter "createPublisherRequest" was null or undefined when calling createPublisher().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/publishers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePublisherRequestToJSON(requestParameters['createPublisherRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperCreatePublisherResponseFromJSON(jsonValue));
    }

    /**
     * Create Publisher
     */
    async createPublisher(requestParameters: CreatePublisherOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperCreatePublisherResponse> {
        const response = await this.createPublisherRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Publishers
     */
    async findPublishersRaw(requestParameters: FindPublishersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPaginatedResponseBasePublisherResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/app/v1/publishers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPaginatedResponseBasePublisherResponseFromJSON(jsonValue));
    }

    /**
     * Find Publishers
     */
    async findPublishers(requestParameters: FindPublishersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPaginatedResponseBasePublisherResponse> {
        const response = await this.findPublishersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft Delete Publisher
     */
    async softDeletePublisherRaw(requestParameters: SoftDeletePublisherRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperSoftDeletePublisherResponse>> {
        if (requestParameters['publisherId'] == null) {
            throw new runtime.RequiredError(
                'publisherId',
                'Required parameter "publisherId" was null or undefined when calling softDeletePublisher().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/publishers/{publisher_id}`.replace(`{${"publisher_id"}}`, encodeURIComponent(String(requestParameters['publisherId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperSoftDeletePublisherResponseFromJSON(jsonValue));
    }

    /**
     * Soft Delete Publisher
     */
    async softDeletePublisher(requestParameters: SoftDeletePublisherRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperSoftDeletePublisherResponse> {
        const response = await this.softDeletePublisherRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Publisher
     */
    async updatePublisherRaw(requestParameters: UpdatePublisherOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUpdatePublisherResponse>> {
        if (requestParameters['publisherId'] == null) {
            throw new runtime.RequiredError(
                'publisherId',
                'Required parameter "publisherId" was null or undefined when calling updatePublisher().'
            );
        }

        if (requestParameters['updatePublisherRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePublisherRequest',
                'Required parameter "updatePublisherRequest" was null or undefined when calling updatePublisher().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/publishers/{publisher_id}`.replace(`{${"publisher_id"}}`, encodeURIComponent(String(requestParameters['publisherId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePublisherRequestToJSON(requestParameters['updatePublisherRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUpdatePublisherResponseFromJSON(jsonValue));
    }

    /**
     * Update Publisher
     */
    async updatePublisher(requestParameters: UpdatePublisherOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUpdatePublisherResponse> {
        const response = await this.updatePublisherRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * View Publisher Detail
     */
    async viewPublisherDetailRaw(requestParameters: ViewPublisherDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperViewPublisherDetailResponse>> {
        if (requestParameters['publisherId'] == null) {
            throw new runtime.RequiredError(
                'publisherId',
                'Required parameter "publisherId" was null or undefined when calling viewPublisherDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/app/v1/publishers/{publisher_id}`.replace(`{${"publisher_id"}}`, encodeURIComponent(String(requestParameters['publisherId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperViewPublisherDetailResponseFromJSON(jsonValue));
    }

    /**
     * View Publisher Detail
     */
    async viewPublisherDetail(requestParameters: ViewPublisherDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperViewPublisherDetailResponse> {
        const response = await this.viewPublisherDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
