/* tslint:disable */
/* eslint-disable */
/**
 * bukoo
 * My Project Description
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChangePasswordRequest,
  ErrorResponse,
  ForceSetUserPasswordRequest,
  RegisterAdminRequest,
  ResponseWrapperAddressResponse,
  ResponseWrapperChangePasswordResponse,
  ResponseWrapperForceSetUserPasswordResponse,
  ResponseWrapperPaginatedResponseReviewWithBookItemResponse,
  ResponseWrapperPaginatedResponseUserListItemResponse,
  ResponseWrapperSoftDeleteMeResponse,
  ResponseWrapperSoftDeleteUserResponse,
  ResponseWrapperUpdateMyReviewResponse,
  ResponseWrapperUserProfileResponse,
  UpdateMyReviewRequest,
  UpdateProfileRequest,
  UpsertAddressRequest,
  UserRole,
  UserStatus,
} from '../models/index';
import {
    ChangePasswordRequestFromJSON,
    ChangePasswordRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ForceSetUserPasswordRequestFromJSON,
    ForceSetUserPasswordRequestToJSON,
    RegisterAdminRequestFromJSON,
    RegisterAdminRequestToJSON,
    ResponseWrapperAddressResponseFromJSON,
    ResponseWrapperAddressResponseToJSON,
    ResponseWrapperChangePasswordResponseFromJSON,
    ResponseWrapperChangePasswordResponseToJSON,
    ResponseWrapperForceSetUserPasswordResponseFromJSON,
    ResponseWrapperForceSetUserPasswordResponseToJSON,
    ResponseWrapperPaginatedResponseReviewWithBookItemResponseFromJSON,
    ResponseWrapperPaginatedResponseReviewWithBookItemResponseToJSON,
    ResponseWrapperPaginatedResponseUserListItemResponseFromJSON,
    ResponseWrapperPaginatedResponseUserListItemResponseToJSON,
    ResponseWrapperSoftDeleteMeResponseFromJSON,
    ResponseWrapperSoftDeleteMeResponseToJSON,
    ResponseWrapperSoftDeleteUserResponseFromJSON,
    ResponseWrapperSoftDeleteUserResponseToJSON,
    ResponseWrapperUpdateMyReviewResponseFromJSON,
    ResponseWrapperUpdateMyReviewResponseToJSON,
    ResponseWrapperUserProfileResponseFromJSON,
    ResponseWrapperUserProfileResponseToJSON,
    UpdateMyReviewRequestFromJSON,
    UpdateMyReviewRequestToJSON,
    UpdateProfileRequestFromJSON,
    UpdateProfileRequestToJSON,
    UpsertAddressRequestFromJSON,
    UpsertAddressRequestToJSON,
    UserRoleFromJSON,
    UserRoleToJSON,
    UserStatusFromJSON,
    UserStatusToJSON,
} from '../models/index';

export interface ActivateUserRequest {
    userId: string;
}

export interface ChangePasswordOperationRequest {
    changePasswordRequest: ChangePasswordRequest;
}

export interface FindMyReviewsRequest {
    sort?: string | null;
    page?: number;
    pageSize?: number;
    search?: string | null;
}

export interface FindUsersRequest {
    sort?: string | null;
    page?: number;
    pageSize?: number;
    search?: string | null;
    role?: UserRole | null;
    status?: UserStatus | null;
}

export interface ForceSetUserPasswordOperationRequest {
    userId: string;
    forceSetUserPasswordRequest: ForceSetUserPasswordRequest;
}

export interface RegisterAdminOperationRequest {
    registerAdminRequest: RegisterAdminRequest;
}

export interface SoftDeleteMyReviewRequest {
    reviewId: string;
}

export interface SoftDeleteUserRequest {
    userId: string;
}

export interface SuspendUserRequest {
    userId: string;
}

export interface UpdateAvatarRequest {
    file: string;
}

export interface UpdateMyReviewOperationRequest {
    reviewId: string;
    updateMyReviewRequest: UpdateMyReviewRequest;
}

export interface UpdateProfileOperationRequest {
    updateProfileRequest: UpdateProfileRequest;
}

export interface UpsertAddressOperationRequest {
    upsertAddressRequest: UpsertAddressRequest;
}

export interface ViewUserProfileRequest {
    userId: string;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Activate User
     */
    async activateUserRaw(requestParameters: ActivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUserProfileResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling activateUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/{user_id}/activate`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Activate User
     */
    async activateUser(requestParameters: ActivateUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUserProfileResponse> {
        const response = await this.activateUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change Password
     */
    async changePasswordRaw(requestParameters: ChangePasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperChangePasswordResponse>> {
        if (requestParameters['changePasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'changePasswordRequest',
                'Required parameter "changePasswordRequest" was null or undefined when calling changePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me/password`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordRequestToJSON(requestParameters['changePasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperChangePasswordResponseFromJSON(jsonValue));
    }

    /**
     * Change Password
     */
    async changePassword(requestParameters: ChangePasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperChangePasswordResponse> {
        const response = await this.changePasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find My Reviews
     */
    async findMyReviewsRaw(requestParameters: FindMyReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPaginatedResponseReviewWithBookItemResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me/reviews`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPaginatedResponseReviewWithBookItemResponseFromJSON(jsonValue));
    }

    /**
     * Find My Reviews
     */
    async findMyReviews(requestParameters: FindMyReviewsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPaginatedResponseReviewWithBookItemResponse> {
        const response = await this.findMyReviewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Find Users
     */
    async findUsersRaw(requestParameters: FindUsersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperPaginatedResponseUserListItemResponse>> {
        const queryParameters: any = {};

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['role'] != null) {
            queryParameters['role'] = requestParameters['role'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperPaginatedResponseUserListItemResponseFromJSON(jsonValue));
    }

    /**
     * Find Users
     */
    async findUsers(requestParameters: FindUsersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperPaginatedResponseUserListItemResponse> {
        const response = await this.findUsersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Force Set User Password
     */
    async forceSetUserPasswordRaw(requestParameters: ForceSetUserPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperForceSetUserPasswordResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling forceSetUserPassword().'
            );
        }

        if (requestParameters['forceSetUserPasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'forceSetUserPasswordRequest',
                'Required parameter "forceSetUserPasswordRequest" was null or undefined when calling forceSetUserPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/{user_id}/password-reset`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ForceSetUserPasswordRequestToJSON(requestParameters['forceSetUserPasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperForceSetUserPasswordResponseFromJSON(jsonValue));
    }

    /**
     * Force Set User Password
     */
    async forceSetUserPassword(requestParameters: ForceSetUserPasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperForceSetUserPasswordResponse> {
        const response = await this.forceSetUserPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Me
     */
    async getMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUserProfileResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Get Me
     */
    async getMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUserProfileResponse> {
        const response = await this.getMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get My Address
     */
    async getMyAddressRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperAddressResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me/address`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperAddressResponseFromJSON(jsonValue));
    }

    /**
     * Get My Address
     */
    async getMyAddress(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperAddressResponse> {
        const response = await this.getMyAddressRaw(initOverrides);
        return await response.value();
    }

    /**
     * Register Admin
     */
    async registerAdminRaw(requestParameters: RegisterAdminOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUserProfileResponse>> {
        if (requestParameters['registerAdminRequest'] == null) {
            throw new runtime.RequiredError(
                'registerAdminRequest',
                'Required parameter "registerAdminRequest" was null or undefined when calling registerAdmin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/admin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterAdminRequestToJSON(requestParameters['registerAdminRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Register Admin
     */
    async registerAdmin(requestParameters: RegisterAdminOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUserProfileResponse> {
        const response = await this.registerAdminRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove Avatar
     */
    async removeAvatarRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUserProfileResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me/avatar`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Remove Avatar
     */
    async removeAvatar(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUserProfileResponse> {
        const response = await this.removeAvatarRaw(initOverrides);
        return await response.value();
    }

    /**
     * Soft Delete Me
     */
    async softDeleteMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperSoftDeleteMeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperSoftDeleteMeResponseFromJSON(jsonValue));
    }

    /**
     * Soft Delete Me
     */
    async softDeleteMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperSoftDeleteMeResponse> {
        const response = await this.softDeleteMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Soft Delete My Review
     */
    async softDeleteMyReviewRaw(requestParameters: SoftDeleteMyReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['reviewId'] == null) {
            throw new runtime.RequiredError(
                'reviewId',
                'Required parameter "reviewId" was null or undefined when calling softDeleteMyReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me/reviews/{review_id}`.replace(`{${"review_id"}}`, encodeURIComponent(String(requestParameters['reviewId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft Delete My Review
     */
    async softDeleteMyReview(requestParameters: SoftDeleteMyReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.softDeleteMyReviewRaw(requestParameters, initOverrides);
    }

    /**
     * Soft Delete User
     */
    async softDeleteUserRaw(requestParameters: SoftDeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperSoftDeleteUserResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling softDeleteUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/{user_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperSoftDeleteUserResponseFromJSON(jsonValue));
    }

    /**
     * Soft Delete User
     */
    async softDeleteUser(requestParameters: SoftDeleteUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperSoftDeleteUserResponse> {
        const response = await this.softDeleteUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Suspend User
     */
    async suspendUserRaw(requestParameters: SuspendUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUserProfileResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling suspendUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/{user_id}/suspend`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Suspend User
     */
    async suspendUser(requestParameters: SuspendUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUserProfileResponse> {
        const response = await this.suspendUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Avatar
     */
    async updateAvatarRaw(requestParameters: UpdateAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUserProfileResponse>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling updateAvatar().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/app/v1/users/me/avatar`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Update Avatar
     */
    async updateAvatar(requestParameters: UpdateAvatarRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUserProfileResponse> {
        const response = await this.updateAvatarRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update My Review
     */
    async updateMyReviewRaw(requestParameters: UpdateMyReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUpdateMyReviewResponse>> {
        if (requestParameters['reviewId'] == null) {
            throw new runtime.RequiredError(
                'reviewId',
                'Required parameter "reviewId" was null or undefined when calling updateMyReview().'
            );
        }

        if (requestParameters['updateMyReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'updateMyReviewRequest',
                'Required parameter "updateMyReviewRequest" was null or undefined when calling updateMyReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me/reviews/{review_id}`.replace(`{${"review_id"}}`, encodeURIComponent(String(requestParameters['reviewId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMyReviewRequestToJSON(requestParameters['updateMyReviewRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUpdateMyReviewResponseFromJSON(jsonValue));
    }

    /**
     * Update My Review
     */
    async updateMyReview(requestParameters: UpdateMyReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUpdateMyReviewResponse> {
        const response = await this.updateMyReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Profile
     */
    async updateProfileRaw(requestParameters: UpdateProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUserProfileResponse>> {
        if (requestParameters['updateProfileRequest'] == null) {
            throw new runtime.RequiredError(
                'updateProfileRequest',
                'Required parameter "updateProfileRequest" was null or undefined when calling updateProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProfileRequestToJSON(requestParameters['updateProfileRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * Update Profile
     */
    async updateProfile(requestParameters: UpdateProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUserProfileResponse> {
        const response = await this.updateProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upsert Address
     */
    async upsertAddressRaw(requestParameters: UpsertAddressOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperAddressResponse>> {
        if (requestParameters['upsertAddressRequest'] == null) {
            throw new runtime.RequiredError(
                'upsertAddressRequest',
                'Required parameter "upsertAddressRequest" was null or undefined when calling upsertAddress().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/me/address`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertAddressRequestToJSON(requestParameters['upsertAddressRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperAddressResponseFromJSON(jsonValue));
    }

    /**
     * Upsert Address
     */
    async upsertAddress(requestParameters: UpsertAddressOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperAddressResponse> {
        const response = await this.upsertAddressRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * View User Profile
     */
    async viewUserProfileRaw(requestParameters: ViewUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseWrapperUserProfileResponse>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling viewUserProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/app/v1/users/{user_id}`.replace(`{${"user_id"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseWrapperUserProfileResponseFromJSON(jsonValue));
    }

    /**
     * View User Profile
     */
    async viewUserProfile(requestParameters: ViewUserProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseWrapperUserProfileResponse> {
        const response = await this.viewUserProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
